---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent
spec:
  version: ${KUBERNETES_VERSION}
  serviceAccountName: system-upgrade-controller
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/os, operator: In, values: ["linux"]}
      - {key: node-role.kubernetes.io/control-plane, operator: NotIn, values: ["true"]}
  tolerations:
  - key: "homelab.k8s.io/type"
    operator: "Equal"
    value: "vm"
    effect: "NoExecute"
  drain:
    force: true
  upgrade:
    image: rancher/rke2-upgrade
  prepare:
    image: rancher/rke2-upgrade
    args: ["prepare", "server"]
