apiVersion: v1
kind: Secret
metadata:
    name: ns-network-secret
stringData:
    K8SGTWDOMAINS: ENC[AES256_GCM,data:qO3ruzf8sw+G5sa4lzah0hbtfLvwh9PKpsF79keWc8jC8WZuWe6FWfzx242xc4SjjUifxSDk,iv:nNTrTl0iY67ed70DO9xqNp2P/rw80Lt0cY2I8hRA114=,tag:eItrWeyuwRA/nHppJkEduQ==,type:str]
    CERT_MAIN_DOMAIN: ENC[AES256_GCM,data:FCJV/moibhG0sPmfAxr0,iv:xJ7ccHtJwcqS9DF1N2WN3WKFmud0yD4+Wwbj1EwbgIE=,tag:EHqtPUTOX/dKVZYDB8pbSg==,type:str]
    CERT_DOMAIN: ENC[AES256_GCM,data:HBuZylgVGKfUHw==,iv:DxZUn3/XPFl4RqrLRmNnQ15JVohtgZsmvn0jODXpdS4=,tag:c5wnQ5TJlFI6Y+bsGhyZlw==,type:str]
    CERT_DEV_DOMAIN: ENC[AES256_GCM,data:qi1alFxchps=,iv:aW//zmQF//H6RIksPAmFSStgeqdYYTxDVeVxZoxd9x0=,tag:IOF4f347A7exDE0bhWypCg==,type:str]
    CERT_GAME_DOMAIN: ENC[AES256_GCM,data:nGiE226Sywk=,iv:BPHF+iIjdm55BdMue8fCaR1evWDjCryaM+9PZ/5fcfk=,tag:KRzJ89NTcplEaKQ7+7l6GA==,type:str]
    CERT_S3_DOMAIN: ENC[AES256_GCM,data:NHgCdGvFgwuYcFtSPg==,iv:59CMaJ5u52beiIqRpe02FMI5tgI80SGvHFAznuMMCVE=,tag:s/Le9/B9VcTItbtBQlXNEA==,type:str]
    CERT_S3_WEB_DOMAIN: ENC[AES256_GCM,data:+9fzWqdxa+nBhE30dcw=,iv:+/gJ3sKqM98j6BZnZ/GjgagsWgZPOIwZ3Ar8PSQsWTs=,tag:Z6csaTHpVmXdHowQ1OyR/g==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T19:10:23Z"
    mac: ENC[AES256_GCM,data:fbUfspoGcLQk6j4RbmiDEjjvwuuh6tj2nQ6/OND3x5MYfvP1J6PxV3ieRU32BhXaosgag8dkpsGyZbz2K/J1wfXuSQUiPrvrN4hbu8FuXtwRKrvPZWs5Xc5nqxx7GmvP4OZNeZNTxlgzXJQ6/DzkzlVGGP2leTcSxiv/5NNDR0A=,iv:TU+VF/Qt4PGOD1PG4jdhctyAL8SuEBJdHIfzUeDg/kE=,tag:7stR8wGS9N2WN55Bd2AQ3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
