apiVersion: v1
kind: Secret
metadata:
    name: cert-main-secret
stringData:
    DOMAIN: ENC[AES256_GCM,data:4EHl4i4bBwFcwZIQ6Q0Z,iv:Yb3wxZj/ZQr1VRahG6Iv0+oJK9o0fsbfdmILtX5YfYc=,tag:1Ov52KGO3IVVcTZw/6+e0A==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T21:22:39Z"
    mac: ENC[AES256_GCM,data:wFCzikAD+HcjDptcIo3bMUb0BBWWyGSYNdEqzO8sFrrl5plDtIFfeCdxsqWzdrfKkQyqPRLoce5PBVdOCx5RL3en4kAXlUjBwdR6A5wSJVB57FiukVLehmqRSlieWC/iJN37N0CZ38PsTfkd5+UE0DVQJE+LN1H99Mso7b2LU1k=,iv:OIz6t7jkqFZlXd9ESnNgOA5RpnXBXceAD4R5q44Z1WI=,tag:bKbclS57Gd8VbI0gLhwZfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
