---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-main-secrets.sops.yaml
  - ./cert-base-secrets.sops.yaml
  - ./cert-dev-secrets.sops.yaml
  - ./cert-game-secrets.sops.yaml
