---
- name: Node exporter
  block:
    # - name: Limit the repo to only install node-exporter packages
    #   vars:
    #     archive: '{{ "unstable" if ansible_distribution == "Debian" else "plucky" }}'
    #     packages:
    #       - prometheus-node-exporter
    #       - prometheus-node-exporter-collectors
    #       - '{{ "dash" if ansible_distribution == "Ubuntu" else "" }}'
    #     package_entries: '{{ packages | select() | join(" ") }}'
    #   ansible.builtin.blockinfile:
    #     path: "{{ apt_preferences_dir }}/50-node-exporter-pinning"
    #     mode: 0644
    #     create: true
    #     block: |
    #       Package: *
    #       Pin: release a={{ archive }}
    #       Pin-Priority: -1
    #       Package: {{ package_entries }}
    #       Pin: release a={{ archive }}
    #       Pin-Priority: 500
    # # The version on stable is archaic
    # - name: Add Debian unstable repository
    #   ansible.builtin.apt_repository:
    #     repo: deb http://ftp.us.debian.org/debian unstable main
    #     state: present
    #     filename: debian-unstable
    #     update_cache: true
    #   when: ansible_distribution == "Debian"
    # - name: Add Ubuntu plucky repository
    #   ansible.builtin.apt_repository:
    #     repo: deb http://archive.ubuntu.com/ubuntu plucky main universe
    #     state: present
    #     filename: ubuntu-plucky
    #     update_cache: true
    #   when: ansible_distribution == "Ubuntu"
    - name: Check if an IPMI device exists
      ansible.builtin.stat:
        path: /sys/class/ipmi
      register: ipmi_class
      changed_when: false
    - name: Install IPMI dependencies
      ansible.builtin.apt:
        name:
          - ipmitool
        state: present
        update_cache: true
        cache_valid_time: 600
        autoclean: true
        autoremove: true
      when: ipmi_class.stat.exists
    - name: Install node-exporter, collectors, and dependencies
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - prometheus-node-exporter-collectors
          - nvme-cli
          - smartmontools
        state: present
        update_cache: true
        cache_valid_time: 600
        autoclean: true
        autoremove: true
    - name: Configure node-exporter
      ansible.builtin.copy:
        dest: /etc/default/prometheus-node-exporter
        content: |
          ARGS="--web.listen-address={{listening_address}}:9100"
        owner: root
        group: root
        mode: 0644
      register: config_file
    - name: Restart the prometheus-node-exporter service
      ansible.builtin.systemd:
        name: prometheus-node-exporter
        state: restarted
      when: config_file.changed
    # This is all kinds of broken on nvme-cli v2.8
    # This PR fixed compat with v2.11 and broke everything earlier:
    # https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/pull/227
    - name: Disable the prometheus-node-exporter-nvme timer
      ansible.builtin.systemd:
        name: prometheus-node-exporter-nvme.timer
        enabled: false
        state: stopped
