---
# placeholder for hashicorp vault
# check login, pull secret (json, value), push secret, sync?
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
vars:
  VAULT_FILE: "{{.ROOT_DIR}}/.secrets/vault.yaml"

  VAULT_ADDR:
    sh: yq -r '.vault.address' {{.VAULT_FILE}}

  VAULT_TOKEN:
    sh: yq -r '.vault.token' {{.VAULT_FILE}}

env:
  VAULT_ADDR: "{{.VAULT_ADDR}}"
  VAULT_TOKEN: "{{.VAULT_TOKEN}}"

tasks:
  vault:
    desc: Ensure valid Vault login (auto-login or fail)
    preconditions:
      - sh: test -f {{.VAULT_FILE}}
        msg: "Missing {{.VAULT_FILE}}"
    cmds:
      - |
        if vault token lookup >/dev/null 2>&1; then
          echo "✔ Vault login valid"
        else
          echo "🔐 Vault login invalid, attempting login…"
          vault login -address="{{.VAULT_ADDR}}" "{{.VAULT_TOKEN}}" \
            >/dev/null || {
              echo "❌ Vault login failed"
              exit 1
            }
        fi

  ensure:
    desc: Ensure valid Vault login (auto-login or fail)
    preconditions:
      - sh: test -f {{.VAULT_FILE}}
        msg: "Missing {{.VAULT_FILE}}"
    cmds:
      - |
          if vault token lookup >/dev/null 2>&1; then
            echo "✔ Vault login valid" >&2
            exit 0
          fi

          echo "🔐 Vault login invalid, attempting login…" >&2
          vault login -address="{{.VAULT_ADDR}}" "{{.VAULT_TOKEN}}" >/dev/null 2>&1 || {
            echo "❌ Vault login failed" >&2
            exit 1
          }
  read:
    desc: Read secret from Vault
    deps:
      - ensure
    cmds:
      - vault kv get -mount=Kubernetes talos-main

  read-latest:
    desc: Read latest secret version from Vault (KV v2) with version proof
    deps:
      - ensure
    preconditions:
      - sh: which jq
        msg: "Missing jq"
    cmds:
      - |
        current_version="$(vault kv metadata get -mount=Kubernetes -format=json talos-main | jq -r '.data.current_version')"
        echo "Current Vault version: ${current_version}"s
        vault kv get -mount=Kubernetes -version="${current_version}" talos-main

  inject:
    desc: Replace vault:// refs in stdin using Vault KV v2
    deps:
      - ensure
    silent: true
    interactive: true
    cmds:
      - |
        {{.SCRIPTS_DIR}}/vault-inject.py

