---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spoolman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: spoolman-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        #===DATABASE CONFIGURATION===
        SPOOLMAN_DB_TYPE: postgres
        SPOOLMAN_DB_NAME: "{{ .SPOOLMAN_POSTGRES_DB }}"
        SPOOLMAN_DB_HOST: "{{ .SPOOLMAN_POSTGRES_HOST }}"
        SPOOLMAN_DB_PASSWORD: "{{ .SPOOLMAN_POSTGRES_PASSWORD }}"
        SPOOLMAN_DB_PORT: "5432"
        SPOOLMAN_DB_USERNAME: "{{ .SPOOLMAN_POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/spoolman


