---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  path: ./kubernetes/apps/base/observability/kube-prometheus-stack
  components:
    #- ../../../../components/envoy/oidc/authentik/internal
    - ../../../../components/ext-auth
    #- ../../../../components/ext-auth/two
  postBuild:
    substitute:
      # for ext auth
      APP: prometheus
      #APP_UPPER: PROMETHEUS
      #APP_SLUG: prometheus
      ALERTMANAGER_SUBDOMAIN: alertmanager
      CLUSTER: ${CLUSTER}
      PVC_CAPACITY: "75"
      STORAGECLASS: local-hostpath
      SUBDOMAIN: prometheus
      GATEWAY: "envoy-internal"
      # INGRESSCLASS: iot-nginx
      EXT_AUTH_TARGET: kube-prometheus-stack-prometheus
      #EXT_AUTH_TARGET_2: kube-prometheus-stack-alertmanager
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      #- kind: Secret
      #  name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alertmanager-auth
spec:
  interval: 1h
  path: ./kubernetes/apps/base/virtual/common
  components:
    - ../../../../components/ext-auth
    #- ../../../../components/envoy/oidc/authentik/internal
  dependsOn:
    - name: kube-prometheus-stack
  postBuild:
    substitute:
      # for ext auth
      APP: alertmanager
      #APP_UPPER: ALERTMANAGER
      #APP_SLUG: alertmanager
      CLUSTER: ${CLUSTER}
      SUBDOMAIN: alertmanager
      EXT_AUTH_TARGET: kube-prometheus-stack-alertmanager
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      #- kind: Secret
      #  name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
