---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../../components/common
  - ../../../vars/main/cluster
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - ./fluent-bit.yaml
  #- ./gatus.yaml
  - ./grafana.yaml
  - ./karma.yaml
  - ./keda.yaml
  - ./kromgo.yaml

  - ./kube-prometheus-stack.yaml
  # TODO seperate scrape config? ./kube-prometheus-stack-scrapeconfig.yaml


  - ./silence-operator.yaml
  - ./victoria-logs.yaml
  # Exporters
  - ./exporters
