---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${CLAIM:-${APP}}
spec:
  storageClassName: ${CLAIM:-${APP}}-storageclass
  accessModes:
    - ${VOL_ACCESSMODES:-ReadWriteMany}
  capacity:
    storage: ${VOL_CAPACITY:-18T}
  #mountOptions:
  #  - local_lock=posix
  #  - nfsvers=4.1
  nfs:
    server: "${NFS_SERVER:-nas.main.internal}"
    path: "${NFS_PATH:-/mnt/user/applications}/${NFS_SUBFOLDER:-${APP}}"
