---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${CLAIM:-${APP}}"
spec:
  accessModes: ["${VOL_ACCESSMODES:-ReadWriteMany}"]
  resources:
    requests:
      storage: "${VOL_CAPACITY:=5Gi}"
  storageClassName: ${CLAIM:-${APP}}-storageclass

