#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jellyfin-config
#  labels:
#    app.kubernetes.io/name: jellyfin
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
#  storageClassName: sc-standard
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-transcode
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: sc-standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: sc-standard
