---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: part-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: part-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: 'mysql://partdb:{{ .sql_partdb }}@mysql-cluster-mysql.database.svc.cluster.local:3306/partdb'
        # Please regenerate the APP_KEY value by calling `docker compose run --rm app php artisan key:generate --show`. Copy paste the value here
        PROVIDER_OEMSECRETS_KEY: '{{ .PROVIDER_OEMSECRETS_KEY }}'
  dataFrom:
    - extract:
        key: ${CLUSTER}/partdb
    - extract:
        key: ${CLUSTER}/mysql-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
