---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: "bootstrap/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/scripts:
  - changed-files:
      - any-glob-to-any-file: "scripts/**/*"
area/talos:
  - changed-files:
      - any-glob-to-any-file: "talos/**/*"
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - ".taskfiles/**/*"
          - "Taskfile.yaml"
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - .renovate/**/*
          - .renovaterc.json5
area/terraform:
  - changed-files:
      - any-glob-to-any-file: terraform/**/*
area/ansible:
  - changed-files:
      - any-glob-to-any-file: ansible/**/*
# Clusters
cluster/main:
  - changed-files:
      - any-glob-to-any-file: bootstrap/main/**/*
      - any-glob-to-any-file: kubernetes/main/**/*
      - any-glob-to-any-file: talos/main/**/*
cluster/test:
  - changed-files:
      - any-glob-to-any-file: bootstrap/test/**/*
      - any-glob-to-any-file: kubernetes/test/**/*
      - any-glob-to-any-file: talos/test/**/*
cluster/registry:
  - changed-files:
      - any-glob-to-any-file: bootstrap/registry/**/*
      - any-glob-to-any-file: kubernetes/registry/**/*
      - any-glob-to-any-file: talos/registry/**/*
