---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-ai
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  interval: 15m
  values:
    controllers:
      paperless-ai:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/clusterzx/paperless-ai
              tag: 3.0.7@sha256:25e1c501891e2d409f1df92e64e4e20b379a0197b7cd35cf98b49184d9da6814
            env:
              #PAPERLESS_API_URL: http://paperless.self-hosted.svc.cluster.local:8000/api
              PAPERLESS_API_URL: https://dms.${SECRET_MAIN_DOMAIN_NAME}/api
              AI_PROVIDER: ollama
              SCAN_INTERVAL: "*/30 * * * *"
              PROCESS_PREDEFINED_DOCUMENTS: yes
              ADD_AI_PROCESSED_TAG: yes
              AI_PROCESSED_TAG_NAME: ai-processed
              USE_PROMPT_TAGS: yes
              TAGS: AI
              USE_EXISTING_DATA: yes
              OLLAMA_API_URL: http://${SECRET_AI1_IP}:11434
              # llama3.2 or phi4
              OLLAMA_MODEL: llama3.2:3b
              RESTRICT_TO_EXISTING_TAGS: yes
              RESTRICT_TO_EXISTING_DOCUMENT_TYPES: yes
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 700m
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        fsGroup: ${APP_GID:=1000}
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: ${APP_GID:=1000}
        runAsNonRoot: true
        runAsUser: ${APP_UID:=1000}
        seccompProfile: { type: RuntimeDefault }
      affinity:
        # Image not yet built for arm64
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
    service:
      app:
        ports:
          http:
            port: 3000
    route:
      app:
        hostnames: ["paperless-ai.${SECRET_MAIN_DOMAIN_NAME}"]
        parentRefs:
          - name: main
            namespace: network
            sectionName: https
    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /app/data
      tmpfs:
        advancedMounts:
          paperless-ai:
            app:
              - path: /app/logs
                subPath: logs
              - path: /app/OPENAPI
                subPath: openai
              - path: /app/public/images
                subPath: cache
              - path: /home/node/.pm2
                subPath: home
              - path: /home/node/nltk_data
                subPath: nltk_data
              - path: /tmp
                subPath: tmp
        enabled: true
        type: emptyDir
