apiVersion: v1
kind: Config
clusters:
  - name: ${cluster}-cluster
    cluster:
      certificate-authority-data: ${KUBE_CA}
      server: ${KUBE_API}
contexts:
  - name: ${cluster}-context
    context:
      cluster: ${cluster}-cluster
      namespace: ${NAMESPACE}
      user: authentik-user
current-context: ${cluster}-context
users:
  - name: authentik-user
    user:
      token: ${KUBE_TOKEN}
