---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: renovate-operator-secret
    template:
      data:
        # OIDC
        RENOVATE_OPERATOR_OIDC_ISSUER: "{{ .RENOVATE_OPERATOR_OIDC_ISSUER }}"
        RENOVATE_OPERATOR_CLIENT_ID: "{{ .RENOVATE_OPERATOR_CLIENT_ID }}"
        RENOVATE_OPERATOR_CLIENT_SECRET: "{{ .RENOVATE_OPERATOR_CLIENT_SECRET }}"
        RENOVATE_OPERATOR_SESSION_SECRET: "{{ .RENOVATE_OPERATOR_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/renovate-operator
