---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN}"
spec:
  secretName: "cluster-internal-production-tls"
  issuerRef:
    name: ca-internal-cluster-issuer
    kind: ClusterIssuer
  commonName: "${DOMAIN}"
  dnsNames: ["${DOMAIN}", "*.${DOMAIN}"]
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "network"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
