---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jobs
components:
  - ../../../components/common
  - ../../../vars/casa
resources:
  - ./publish-k8s-schemas.yaml

