---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dbgate-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: dbgate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        user: "{{ .user }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/dbgate
