---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: jellyseerr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        API_KEY  : "{{ .JELLYSEERR_APIKEY }}"
        DB_TYPE: "postgres"
        DB_HOST: "{{ .JELLYSEERR_POSTGRES_HOST }}"
        DB_PORT: "5432"
        DB_USER: "{{ .JELLYSEERR_POSTGRES_USER }}"
        DB_PASS: "{{ .JELLYSEERR_POSTGRES_PASSWORD }}"
        DB_NAME: "{{ .JELLYSEERR_POSTGRES_DB }}"

  dataFrom:
    - extract:
        key: ${CLUSTER}/jellyseerr

