---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: jellyseerr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .api_key }}"
        DB_TYPE: "postgres"
        DB_HOST: postgres-cluster-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: "jellyseerr"
        DB_PASS: "{{ .sql_jellyseerr }}"
        DB_NAME: jellyseerr
  dataFrom:
    - extract:
        key: ${CLUSTER}/jellyseerr
    - extract:
        key: ${CLUSTER}/pg-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
