---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyseerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      jellyseerr:
        replicas: ${REPLICAS:=1}
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/fallenbagel/jellyseerr
              tag: 2.7.2@sha256:d83fcc8478f53073008b0c452c87d94ff5182fce73c426c813301c402b6612de
            env:
              LOG_LEVEL: "info"
              PORT: &port 80
              TZ: ${CLUSTER_TIMEZONE}
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 10m
                memory: 350Mi
              limits:
                memory: 600Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["requests.${SECRET_MAIN_DOMAIN_NAME}"]
        parentRefs:
          - name: main
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: jellyseerr
          gethomepage.dev/icon: jellyseerr.png
          gethomepage.dev/description: Media Request Management
          gethomepage.dev/widget.type: jellyseerr
          gethomepage.dev/widget.url: http://jellyseerr.media:80
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_JELLYSEERR_TOKEN}}` }}"
    #ingress:
    #  app:
    #    enabled: ${DEFAULTINGRESSEN:=true}
    #    className: ${INGRESSCLASS}
    #    hosts:
    #      - host: &host "{{ .Release.Name }}.${DOMAIN}"
    #        paths:
    #          - path: /
    #            service:
    #              identifier: app
    #              port: http
    #    tls:
    #      - hosts:
    #          - *host
    #  iot:
    #    enabled: ${IOTINGRESS:=false}
    #    className: iot-nginx
    #    annotations:
    #      gethomepage.dev/enabled: "true"
    #      gethomepage.dev/group: Media
    #      gethomepage.dev/name: jellyseerr
    #      gethomepage.dev/icon: jellyseerr.png
    #      gethomepage.dev/description: Media Request Management
    #      gethomepage.dev/widget.type: jellyseerr
    #      gethomepage.dev/widget.url: http://jellyseerr.media:80
    #      gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_JELLYSEERR_TOKEN}}` }}"
    #      gethomepage.dev/pod-selector: >-
    #        app.kubernetes.io/name in (
    #          jellyseerr
    #        )
    #    hosts:
    #      - host: &host "requests.${SECRET_MAIN_DOMAIN_NAME}"
    #        paths:
    #          - path: /
    #            service:
    #              identifier: app
    #              port: http
    #    tls:
    #      #- secretName: chart-example-tls
    #      - hosts:
    #        - *host

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/config
      cache:
        existingClaim: jellyseerr-cache
        globalMounts:
          - path: /app/config/cache
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
      tmp:
        type: emptyDir
