---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-secret
    template:
      data:
        # Admin User
        GF_SECURITY_ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/grafana
