---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-2
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - cookie
    http:
      backendRefs:
        - name: ak-outpost-authentik-embedded-outpost
          namespace: sso
          port: 9000
      path: /outpost.goauthentik.io/auth/envoy
      headersToBackend:
        - set-cookie
        - x-authentik-*
        - authorization
  targetRefs:
    - group: ${EXT_AUTH_GROUP_2:-gateway.networking.k8s.io}
      kind: ${EXT_AUTH_KIND_2:-HTTPRoute}
      name: ${EXT_AUTH_TARGET_2:-${APP}}
