---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: network # Required for Renovate lookups
spec:
  interval: 2h
  url: https://kubernetes-sigs.github.io/external-dns
  timeout: 3m
