---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kb-minio-credential-for-backuprepo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: kb-minio-credential-for-backuprepo
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accessKeyId: "{{ .kubeblocks_access_key }}"
        secretAccessKey: "{{ .kubeblocks_secret_key }}"
  dataFrom:
    - extract:
        #key: ${CLUSTER}/kubeblocks
        key: readonly/minio/backup
