apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: BackupRepo
metadata:
  name: minio-repo
  annotations:
    dataprotection.kubeblocks.io/is-default-repo: "true"
spec:
  storageProviderRef: minio
  accessMethod: Tool
  pvReclaimPolicy: Retain
  volumeCapacity: 100Gi
  config:
    bucket: kb-backup
    mountOptions: ""
    endpoint: ${MINIOSERVER}
    insecure: "true"
  credential:
    name: kb-minio-credential-for-backuprepo
    namespace: database
