---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${SECRET_STORE:-vault-backend}
  target:
    name: ${APP}-oidc-secret
    template:
      data:
        client-id: "{{ .${APP_UPPER}_OIDC_CLIENT_ID }}"
        client-secret: "{{ .${APP_UPPER}_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/${APP}
