---
# yaml-language-server: $schema=https://schemas.sstr.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-oidc
spec:
  targetRefs:
    - group: ${EXT_AUTH_GROUP:-gateway.networking.k8s.io}
      kind: ${EXT_AUTH_KIND:-HTTPRoute}
      name: ${EXT_AUTH_TARGET:-${APP}}
  oidc:
    provider:
      issuer: "https://${SECRET_SSO_DOMAIN}/application/o/${APP_SLUG:-${APP}}/"
    clientIDRef:
      kind: Secret
      name: ${APP}-oidc-secret
    clientSecret:
      name: ${APP}-oidc-secret
    # redirectURL: "https://${APP}.${APP_DOMAIN}/oauth2/callback"
    refreshToken: true
    # cookieDomain: ${APP_DOMAIN}
    logoutPath: "${LOGOUT_PATH:-/logout}"
    scopes:
      - openid
      - profile
      - email
      #- offline_access
