apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cS9ve/JGONg=,iv:3mUh3OkBOeIkrhSxRiXtwVkgjz/lwDJZz2PioDl/t/E=,tag:C/WIKB0I30+mXETUqXrU1A==,type:str]
    SECRET_SSO_DOMAIN: ENC[AES256_GCM,data:lTvdRWedQUF9nyYW0A==,iv:92vQdxLr+Y9hfwRDnrScshN/QwT051h3L1zAG5dJubI=,tag:Q0j3K2E1lfmxdwPKECt8CQ==,type:str]
    SECRET_SSO_DOMAIN_2: ENC[AES256_GCM,data:iFy9YJikRU+BhO0=,iv:WX7m++2XUMx3kGAOkApnF4MWBlEuIMHO+/FYEOhoWd4=,tag:EniYa7mOL5IMHUCJUHQC1w==,type:str]
    FLUX_WEBHOOK_EXTERNAL: ENC[AES256_GCM,data:WbF+PQ0Wifj3rBvc4fCNo6mx8K5G6xwKab4YZjjW,iv:JwrT92HYguiAk3VgLHSNKJMuJuZ4e8rn6/f8UP0R8JI=,tag:y+cfeImleJOGwycTDlwoFQ==,type:str]
    SMTP_RELAY_HOST: ENC[AES256_GCM,data:eo8BCVzZZf+JHpDdDD4Oar88KAEOfAIBjc1hCsA3vTORzA==,iv:G0T0hrjjaHfpcWZ8gp2GS/YshtW+s2N6bLR+qwmnDKE=,tag:94W8H7WFgsJrS6lseC9CXg==,type:str]
    SECRET_SMTP_FROM_FULL: ENC[AES256_GCM,data:wp83sH57R2VX5QB4TE1d949eMg==,iv:JRgMv2SWY4sxcbFYZzirSeVrEMhpdxAP3k5bU8402Os=,tag:VQ1vYU7rbB81eMBfqSBPsw==,type:str]
    SECRET_N8NWEBHOOKS_DOMAIN: ENC[AES256_GCM,data:T+UGwj9ijNrjPCOOK/vD/QCfWbiNgg==,iv:DI2emPGKq4P5EW4hmhKhmMMU7hQw9FFhW6i8ALNla8I=,tag:ABCgyVrc/JN6MAyOBAwPuQ==,type:str]
    SECRET_S3_DOMAIN: ENC[AES256_GCM,data:cTrTPIimcA2iKocBUg==,iv:jXJSQDKIJQDfRPQQQM2Csm071BLTsJNWIjknizMcclI=,tag:o8G5DICnkeM72tuHNFXY4g==,type:str]
    SECRET_S3_WEB_DOMAIN: ENC[AES256_GCM,data:fhmYJYy6mOS9xlN/Lks=,iv:xRhQr+M0A7favxiX7Az1d5aVI2sHKIWtLubVvJpnZi8=,tag:ioD61tEqMo013KSR/BjzfQ==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T06:53:04Z"
    mac: ENC[AES256_GCM,data:sk55Lq/0jHRrA8GfVBj7CqZ5re7gvyg+/meITi7z64d6dmp9tbEcOI2RKP/iPLogH7gopjpMFCq5R/iZinfM97CmWo6jnPRdWZoi5sn3ODdMMnbIMV93I2F9pp1iS03cLKWtx/Xw9qHyPBnmLIFFWmOE1yryD3cx1w2FWfSNJnU=,iv:TdCWC5VaTk7VT6y17Ej4m+lpXoAl6j4M6E9R+Cl5EXE=,tag:2z+KOC2wydtNZdI/Rq8XdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
