---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            # Using Multus for static IP on IoT/Wireless network
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-wireless",
                "namespace": "network",
                "ips": ["192.168.188.201/24"],
                "mac": "EA:E6:16:B1:A4:D7"
              }]

          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65542 # gladius:external-services
        #strategy: RollingUpdate
        #type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/scrypted
              tag: 0.141.0@sha256:c9e82faec2e27debeba03fd8d4bdb2aa53cdaf0f3f8aa77c04312a047db4c2ea
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 300M
              limits:
                memory: 8192Mi


    service:
      app:
        ports:
          http:
            port: &port 11080
            primary: true
          rebroadcast1:
            port: 34135
          rebroadcast2:
            port: 34136

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}"
        parentRefs:
          - name: main
            namespace: network
            sectionName: https

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      tmpfs:
        type: emptyDir
        advancedMounts:
          scrypted:
            app:
              - path: /.cache
                subPath: cache
              - path: /.npm
                subPath: npm-cache
      recs:
        existingClaim: scrypted-recs
        globalMounts:
          - path: /recs
