---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: mariadb
spec:
  mariaDbRef:
    name: mariadb
    namespace: database
  privileges:
    - "ALL"
  database: "*"
  table: "*"
  username: mariadb
  host: "%"
  grantOption: true
