---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
    template:
      data:
        # App
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        # postgres
        PAPERLESS_DBPASS: '{{ .sql_paperless }}'
        # sso
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Casa SSO",
                        "client_id": "{{ .PAPERLESS_CLIENT_ID }}",
                        "secret": "{{ .PAPERLESS_CLIENT_SECRET }}",
                        "settings": {
                            "server_url": "https://${SECRET_SSO_DOMAIN}/application/o/dms/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
  dataFrom:
    - extract:
        key: ${CLUSTER}/paperless
    - extract:
        key: ${CLUSTER}/pg-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
