---
# yaml-language-server: $schema=https://schemas.sstr.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-driver-nfs
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.13.2
  url: oci://ghcr.io/home-operations/charts-mirror/csi-driver-nfs
---
# yaml-language-server: $schema=https://schemas.sstr.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  interval: 1h
  values:
    controller:
      runOnControlPlane: false
    externalSnapshotter:
      enabled: false
    node:
      tolerations: []
    storageClass:
      create: false

    ## StorageClass resources for creating multiple storage classes:
    storageClasses:
      - name: nfs-delete
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
        parameters:
          server: nas.main.internal
          share: /mnt/user/kubernetes
          # double $ sign to avoid flux variable substitution
          #subDir: delete/$${pvc.metadata.namespace}-$${pvc.metadata.name}
          subDir: delete/${pvc.metadata.namespace}-${pvc.metadata.name}
          # subDir:
          # mountPermissions: "0"
          # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
          # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
          # csi.storage.k8s.io/provisioner-secret-namespace: "default"
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        mountOptions: &mountOptions
          - nfsvers=4.2
          - nconnect=16
          - hard
          - noatime
      - name: nfs-retain
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
        parameters:
          server: nas.main.internal
          share: /mnt/user/kubernetes
          # double $ sign to avoid flux variable substitution
          #subDir: retain/$${pvc.metadata.namespace}-$${pvc.metadata.name}
          subDir: retain/${pvc.metadata.namespace}-${pvc.metadata.name}
          # subDir:
          # mountPermissions: "0"
          # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
          # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
          # csi.storage.k8s.io/provisioner-secret-namespace: "default"
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        mountOptions: *mountOptions
