---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gotenberg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: gotenberg/gotenberg
              tag: 8.23.2
            command:
              - 'gotenberg'
              - '--chromium-disable-javascript=true'
              - '--chromium-allow-list=file:///tmp/.*'
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 256Mi
    persistence:
      tmp:
        enabled: true
        type: emptyDir

    service:
      app:
        primary: true
        controller: *app
        ports:
          http:
            port: 3000


