---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: teslamate
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        DATABASE_HOST: &dbHost postgres-cluster-rw.database.svc.cluster.local
        DATABASE_NAME: &dbName teslamate
        DATABASE_USER: &dbUser "{{ .POSTGRES_USER }}"
        DATABASE_PASS: &dbPass "{{ .POSTGRES_PASS }}"
        MQTT_HOST: "{{ .MQTT_HOST }}"
        MQTT_USERNAME: "{{ .TESLAMATE_MQTT_USERNAME }}"
        MQTT_PASSWORD: "{{ .TESLAMATE_MQTT_PASSWORD }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER_FLAGS: "-s"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/teslamate
    - extract:
        key: ${CLUSTER}/mqtt
    - extract:
        key: ${CLUSTER}/cloudnative-pg
