---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: teslamate
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        DATABASE_HOST: postgres-rw.database.svc.cluster.local
        DATABASE_NAME: teslamate
        DATABASE_USER: "{{ .TESLAMATE_POSTGRES_USER }}"
        DATABASE_PASS: "{{ .TESLAMATE_POSTGRES_PASS }}"
        MQTT_HOST: "{{ .TESLAMATE_MQTT_HOST }}"
        MQTT_USERNAME: "{{ .TESLAMATE_MQTT_USERNAME }}"
        MQTT_PASSWORD: "{{ .TESLAMATE_MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/teslamate
