---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app n8n
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/automation/n8n
  components:
    - ../../../../components/vol
  postBuild:
    substitute:
      APP: *app
      REPLICAS: "1"

      # webhook: "iot-base-nginx"
      # web: "iot-nginx"
      #ADMIN_INGRESSCLASS: internal-nginx
      #SSO_INGRESSCLASS: "iot-base-nginx"
      VOL_CAPACITY: 1Gi
      VOL_STORAGECLASS: sc-standard
      VOL_ACCESSMODES: ReadWriteMany
      VOL_RESOURCEPOLICY: keep
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: postgres-cluster
      namespace: database
    - name: external-secrets
      namespace: security
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: automation
  timeout: 5m
  wait: true

