---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app convertx
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        replicas: ${REPLICAS:=1}
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          *app :
            image:
              repository: ghcr.io/c4illin/convertx
              tag: v0.14.1
            env:
              AUTO_DELETE_EVERY_N_HOURS: "72"
              ALLOW_UNAUTHENTICATED: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      *app :
        controller: *app
        ports:
          http:
            port: *port

    #ingress:
    #  *app :
    #    className: iot-nginx
    #    annotations:
    #      gethomepage.dev/enabled: "true"
    #      gethomepage.dev/group: Home
    #      gethomepage.dev/name: ConvertX
    #      gethomepage.dev/description: "Self-hosted online file converter"
    #    #  gethomepage.dev/pod-selector: >-
    #    #    app.kubernetes.io/name in (
    #    #      it-tools
    #    #    )
    #    hosts:
    #      - host: &host "{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}"
    #        paths:
    #          - path: /
    #            service:
    #              identifier: *app
    #              port: http
    #    tls:
    #      - hosts:
    #          - *host
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}"]
        parentRefs:
          - name: main
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
        #annotations:
        #  gethomepage.dev/enabled: "true"
        #  gethomepage.dev/group: Home
        #  gethomepage.dev/name: ConvertX
        #  gethomepage.dev/description: "Self-hosted online file converter"

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
