---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name samba
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        samba.yaml: |
          auth:
            - user: {{ .user1name }}
              group: {{ .user1name }}
              uid: 1000
              gid: 1000
              password: {{ .user1pw }}
            - user: {{ .user2name }}
              group: {{ .user1name }}
              uid: 1001
              gid: 1000
              password: {{ .user2pw }}
            - user: {{ .user3name }}
              group: {{ .user1name }}
              uid: 1002
              gid: 1000
              password: {{ .user3pw }}

          share:
            - name: data
              path: /shares/data
              comment: "DMS folder"
              browsable: yes
              readonly: no
              guestok: no
              validusers: {{ .user1name }},{{ .user2name }}
              writelist: {{ .user1name }},{{ .user2name }}
              veto: no
              hidefiles: /_*/
            - name: media
              path: /shares/media
              comment: "Media folder"
              browsable: yes
              readonly: no
              guestok: no
              validusers: {{ .user1name }},{{ .user2name }}
              writelist: {{ .user1name }},{{ .user2name }}
              veto: no
              hidefiles: /_*/
            - name: dms_scans
              path: /shares/data/dms_scans
              comment: "DMS Scans folder"
              browsable: no
              readonly: no
              guestok: no
              validusers: {{ .user3name }},{{ .user1name }}
              writelist: {{ .user3name }},{{ .user1name }}
              veto: no
              hidefiles: /_*/
            - name: dms_import
              path: /shares/data/dms_import
              comment: "DMS import folder"
              browsable: no
              readonly: no
              guestok: no
              validusers: {{ .user3name }},{{ .user1name }}
              writelist: {{ .user3name }},{{ .user1name }}
              veto: no
              hidefiles: /_*/
  dataFrom:
    - extract:
        key: ${CLUSTER}/samba
