apiVersion: v1
kind: Secret
metadata:
    name: ns-dev-secret
stringData:
    SECRET_FORGEJO_GIT_HOSTNAME: ENC[AES256_GCM,data:GNS1fhzaywPRvPIyeetvkg==,iv:eGMA82f0ESfh3JW5v6Otwb9wb3QNc0rSE3y7zjCUb4Y=,tag:MfXk7TzRjgX2kzzG/K1+/Q==,type:str]
    SECRET_FORGEJO_HOSTNAME: ENC[AES256_GCM,data:TMsfFHqlKd9lZRyE1g==,iv:Fv8H9G/6zaIqZVf7ScS/rqNhV2LsGUfEH7iH1XIYipU=,tag:wkCtykZQPe1L0o/bdCSkrA==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T17:43:41Z"
    mac: ENC[AES256_GCM,data:QzrO3QI5PRiUcb9Ugmg4NfKeWO70vog/XOqOpe9Z+sbVlCjIily4GYmWUIERcKUB5rnBBEZqXKZgVt98I7ysYLQmuMs7SYrBwh/Vv1wY8oP25lK7GaoShHlKHXXnoA+8xv5Ml+MLY3TBGCDDUBtVQtYjT8VZNI+HtgHRWipg298=,iv:P/hmCZ2Wm3YWbpLj7Ah2++uX8SSJWbDh5qDs1rllpxo=,tag:+PAsUOgY/+A87wRC8D5Rng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
