
---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-collabora
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nextcloud-collabora-secret
    template:
      data:
        # App
        COLLABORA_ADMIN_USERNAME: "{{ .COLLABORA_ADMIN_USERNAME }}"
        COLLABORA_ADMIN_PASSWORD: "{{ .COLLABORA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/collabora
