---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pve-exporter
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  #components:
  #  - ../../../../../components/ext-auth
  path: ./kubernetes/apps/base/observability/exporters/pve-exporter
  prune: true
  retryInterval: 2m
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  timeout: 5m
  wait: true


