---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: forgejo-runner-secret
    template:
      data:
        RUNNER_NAME: '{{ .FORGEJO_RUNNER_NAME }}'
        RUNNER_TOKEN: '{{ .FORGEJO_RUNNER_TOKEN }}'
  dataFrom:
    - extract:
        key: ${CLUSTER}/forgejo

