---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio-job
spec:
  staticConfigs:
    - targets:
        - minio.storage-system.svc.cluster.local:9000
  metricsPath: /minio/v2/metrics/cluster
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name

