---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: webhook
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JELLYSEERR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .JELLYSEERR_PUSHOVER_TOKEN }}
        RADARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .RADARR_PUSHOVER_TOKEN }}
        SONARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .SONARR_PUSHOVER_TOKEN }}
        SONARR_API_KEY: '{{ .sonarr_api_key }}'
  dataFrom:
    - extract:
        key: ${CLUSTER}/pushover
    - extract:
        key: ${CLUSTER}/sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"

