---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-system
components:
  - ../../../components/common
  - ../../../vars/casa
resources:
  - ./samba.yaml
  - ./snapshot-controller.yaml
  - ./minio.yaml
  - ./democratic-csi.yaml
  - ./local-path-provisioner.yaml

