---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-timescale-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cnpg-timescale-backup-secret
    template:
      data:
        POSTGRES_HOST: "postgres-timescale-rw.database"
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PORT: "5432"
  dataFrom:
    - extract:
        key: ${CLUSTER}/cloudnative-pg
