---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: longhorn
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.11.1
  url: oci://ghcr.io/home-operations/charts-mirror/longhorn
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# /var/mnt/extra/openebs/local
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chartRef:
    kind: OCIRepository
    name: longhorn
  dependsOn: []
  interval: 15m
  values:
    defaultSettings:
      backupTarget: s3://longhorn-backups@home/
      backupTargetCredentialSecret: longhorn-secret
      defaultDataPath: /var/mnt/extra/longhorn
      defaultReplicaCount: "3"
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: true
      restoreVolumeRecurringJobs: true
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: "100000"
      storageMinimalAvailablePercentage: "1"
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: "3"
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      # Recommended for databases with app-level redundancy:
      # This allows the drain to proceed even if the volume is the last replica.
      nodeDrainPolicy: allow-if-replica-is-stopped
      #taintToleration: node-role.kubernetes.io/control-plane:NoSchedule
    #longhornDriver:
    #  tolerations: &tolerations
    #    - key: CriticalAddonsOnly
    #      operator: Exists
    #    - key: node-role.kubernetes.io/control-plane
    #      operator: Exists
    #      effect: NoSchedule
    #longhornManager:
    #  tolerations: *tolerations
    metrics:
      serviceMonitor:
        enabled: true
