---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app change-detection
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.50.14@sha256:d8113bf66f47895d29c6935000bbac4c0f33d79588ae37d9ed6000ed328c5833
            env:
              PORT: &port 5000
              USE_X_SETTINGS: 1
              BASE_URL: &host 'https://{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}'
              PLAYWRIGHT_DRIVER_URL: 'ws://localhost:3000/chrome?stealth=1&--disable-web-security=true'
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 250Mi
          browserless:
            image:
              repository: ghcr.io/browserless/chrome
              tag: v2.36.0@sha256:30ef9f9dfe6ac6ea90553b4a2d90b750927e207fabec44a536f0f53f00668d52
            env:
              TIMEOUT: 60000
            securityContext:
              runAsUser: 999
              runAsGroup: 999
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 1500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - '{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}'
        parentRefs:
          - name: main
            namespace: network
            sectionName: https
        rules:
          - backendRefs: [{}]
    persistence:
      datastore:
        existingClaim: *app
        advancedMounts:
          *app :
            app:
              - path: /datastore
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
