---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
    template:
      data:
        #ALERTMANAGER_HEARTBEAT_URL: "{{ .ALERTMANAGER_${CLUSTER^^}_HEARTBEAT_URL }}"
        ALERTMANAGER_PUSHOVER_TOKEN: '{{ .ALERTMANAGER_PUSHOVER_TOKEN }}'
        PUSHOVER_USER_KEY: '{{ .ALERTMANAGER_PUSHOVER_USER_KEY }}'
        DISCORD_WEBHOOK_URL: "{{ .ALERTMANAGER_DISCORD_WEBHOOK_URL }}"
  dataFrom:
  - extract:
      key: ${CLUSTER}/alertmanager
  - extract:
      key: ${CLUSTER}/discord
