---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drawio
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      drawio:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/jgraph/drawio
              tag: 28.2.0
            env:
              TZ: ${CLUSTER_TIMEZONE}
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    #ingress:
    #  app:
    #    enabled: ${DEFAULTINGRESSEN:=true}
    #    className: ${INGRESSCLASS}
    #    hosts:
    #      - host: &host "{{ .Release.Name }}.${DOMAIN}"
    #        paths:
    #          - path: /
    #            service:
    #              identifier: app
    #              port: *port
    #    tls:
    #      - hosts:
    #          - *host
    #  iot:
    #    enabled: ${IOTINGRESS:=false}
    #    className: iot-nginx
    #    annotations:
    #      gethomepage.dev/enabled: 'true'
    #      gethomepage.dev/group: Home
    #      gethomepage.dev/icon: draw-io.png
    #      gethomepage.dev/name: Drawio
    #      gethomepage.dev/description: "Diagramming Tool"
    #      gethomepage.dev/pod-selector: >-
    #        app.kubernetes.io/name in (
    #          drawio
    #        )
    #    hosts:
    #      - host: &host "{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}"
    #        paths:
    #          - path: /
    #            service:
    #              identifier: app
    #              port: *port
    #    tls:
    #      #- secretName: chart-example-tls
    #      - hosts:
    #        - *host

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}"
        parentRefs:
          - name: main
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
        #annotations:
        #  gethomepage.dev/enabled: 'true'
        #  gethomepage.dev/group: Home
        #  gethomepage.dev/icon: draw-io.png
        #  gethomepage.dev/name: Drawio
        #  gethomepage.dev/description: "Diagramming Tool"
