---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manyfold
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: manyfold-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # https://manyfold.app/sysadmin/configuration.html

        #===GENERIC CONFIGURATION===
        SECRET_KEY_BASE: "{{ .MANYFOLD_SECRET_KEY_BASE }}"

        #===USER CONFIGURATION===
        OIDC_ISSUER: "{{ .MANYFOLD_OIDC_ISSUER }}"
        OIDC_CLIENT_ID: "{{ .MANYFOLD_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MANYFOLD_OIDC_CLIENT_SECRET }}"
        OIDC_NAME: "Authentik"
        FORCE_OIDC: "enabled"


        #===CACHE CONFIGURATION===
        #REDIS_URL: |-
        #  redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/5

        #===DATABASE CONFIGURATION===
        DATABASE_ADAPTER: postgresql
        DATABASE_URL: "postgresql://{{ .MANYFOLD_POSTGRES_USER }}:{{ .MANYFOLD_POSTGRES_PASSWORD }}@{{ .MANYFOLD_POSTGRES_HOST }}/{{ .MANYFOLD_POSTGRES_DB }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/manyfold
    #- extract:
    #    key: ${CLUSTER}/dragonfly

