---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../../components/common
  - ../../../vars/main/settings
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - ./openebs.yaml
  - ./csi-driver-nfs.yaml
  - ./snapshot-controller.yaml
  - ./kopia.yaml
  - ./volsync.yaml
  #- ./volsync-maintenance.yaml

# TODO: volsync (nfs, s3), kopia (s3), garage (ext)
