---
# yaml-language-server: $schema=https://schemas.sstr.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn
spec:
  dependsOn:
    - name: snapshot-controller
  interval: 1h
  path: ./kubernetes/apps/base/storage/longhorn
  components:
    - ../../../../components/envoy/ext-auth
    #- ../../../../components/envoy/oidc/authentik/internal
  prune: true
  postBuild:
    substitute:
      APP: *app
      #APP_UPPER: LONGHORN
      #APP_SLUG: longhorn
      CLUSTER: ${CLUSTER}
      SUBDOMAIN: longhorn
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      #- kind: Secret
      #  name: cluster-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://schemas.sstr.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-jobs
spec:
  dependsOn:
    - name: longhorn
  interval: 1h
  path: ./kubernetes/apps/base/storage/longhorn/jobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
