---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ### Location
        HOMEPAGE_VAR_LATITUDE: "{{ .hp_home_latitude }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .hp_home_longitude }}"

        ### Home
        ## HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_TOKEN }}"
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .paperless_homepage_token }}"

        ### Media
        HOMEPAGE_VAR_JELLYFIN_TOKEN: "{{ .hp_jellyfin_api_key }}"
        HOMEPAGE_VAR_JELLYSEERR_TOKEN: "{{ .jellyseerr_api_key }}"
        #HOMEPAGE_VAR_PLEX_TOKEN: "{{ .plex_PLEX_TOKEN }}"

        ### Downloads
        ## HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .BAZARR__API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .radarr_api_key }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .sonarr_api_key }}"
        HOMEPAGE_VAR_PROWLARR_KEY: "{{ .prowlarr_api_key }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .sabnzbd_api_key }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .lidarr_api_key }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .readarr_api_key }}"
#
#
        ### Gaming
        HOMEPAGE_VAR_PTERODACTYL_KEY: "{{ .hp_pterodactyl_key }}"
#
        ### Observability
        ## HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        ## HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
        ## HOMEPAGE_VAR_HEALTHCHECK_TOKEN: "{{ .HOMEPAGE_VAR_HEALTHCHECK_TOKEN }}"
        ## HOMEPAGE_VAR_HEALTHCHECK_UUID: "{{ .HOMEPAGE_VAR_HEALTHCHECK_UUID }}"
        ### Security
        #HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .authentik_HOMEPAGE_VAR_AUTHENTIK_TOKEN }}"
        ### Tandoor
        #HOMEPAGE_VAR_TANDOOR_API_KEY: "{{ .hp_tandoor_api_key }}"
        ### Mealie
        HOMEPAGE_VAR_MEALIE_API_KEY: "{{ .hp_mealie_api_key }}"



  dataFrom:
    - extract:
        key: ${CLUSTER}/homepage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hp_$1"
    #- extract:
    #    key: ${CLUSTER}/grafana
    #  rewrite:
    #    - regexp:
    #        source: "(.*)"
    #        target: "grafana_$1"
    - extract:
        key: ${CLUSTER}/jellyseerr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "jellyseerr_$1"
    - extract:
        key: ${CLUSTER}/prowlarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "prowlarr_$1"
    - extract:
        key: ${CLUSTER}/radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: ${CLUSTER}/sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
    - extract:
        key: ${CLUSTER}/sabnzbd
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sabnzbd_$1"
    - extract:
        key: ${CLUSTER}/lidarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lidarr_$1"
    - extract:
        key: ${CLUSTER}/readarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "readarr_$1"
    #- extract:
    #    key: ${CLUSTER}/pterodactyl
    #  rewrite:
    #    - regexp:
    #        source: "(.*)"
    #        target: "pterodactyl_$1"
    #- extract:
    #    key: ${CLUSTER}/authentik
    #  rewrite:
    #    - regexp:
    #        source: "(.*)"
    #        target: "authentik_$1"
    - extract:
        key: ${CLUSTER}/paperless
      rewrite:
        - regexp:
            source: "(.*)"
            target: "paperless_$1"
    #- extract:
    #    key: ${CLUSTER}/plex
    #  rewrite:
    #    - regexp:
    #        source: "(.*)"
    #        target: "plex_$1"
