---
# yaml-language-server: $schema=https://schemas.sstr.dev/k8s.mariadb.com/database_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: ${DATABASE:=${APP}}
spec:
  mariaDbRef:
    name: mariadb
    namespace: database
  characterSet: utf8
  collate: utf8_general_ci
