---
# yaml-language-server: $schema=https://schemas.sstr.dev/k8s.mariadb.com/user_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: ${DATABASE:=${APP}}
spec:
  mariaDbRef:
    name: mariadb
    namespace: database
  passwordSecretKeyRef:
    name: ${APP}-mariadb-secret
    key: DB_PASSWORD
  host: "%"
  maxUserConnections: ${MAX_CON:=20}
