---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
    template:
      data:
        # App
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        # postgres
        POSTGRES_SERVER: postgres-cluster-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: mealie
        POSTGRES_PASSWORD: "{{ .sql_mealie }}"
        POSTGRES_DB: mealie
        DB_ENGINE: "postgres"

        # Email
        SMTP_HOST: "smtp-relay.default.svc.cluster.local"
        SMTP_PORT: "25"
        SMTP_FROM_NAME: "Recipes"
        SMTP_FROM_EMAIL: "${SECRET_SMTP_FROM_FULL}"
        SMTP_AUTH_STRATEGY: NONE


        ## bootstrp user
        #DEFAULT_EMAIL: "${ADMIN_EMAIL}"
        #DEFAULT_PASSWORD: "${DEFAULT_PWD}"





        #AUTO_BACKUP_ENABLED: "true"
        # OpenId Connect
        # https://docs.goauthentik.io/integrations/services/mealie/
        OIDC_ADMIN_GROUP: "homelab-admins"
        OIDC_AUTH_ENABLED: "true"
        #OIDC_SIGNUP_ENABLED: true
        OIDC_AUTO_REDIRECT: "true"
        OIDC_CLIENT_ID: "{{ .client_id }}"
        OIDC_CLIENT_SECRET: "{{ .client_secret }}"
        OIDC_CONFIGURATION_URL: "{{ .openid_config }}"
        OIDC_PROVIDER_NAME: "Casa SSO"
        OIDC_REMEMBER_ME: "true"
        OIDC_USER_GROUP: "mealie-users"
        #OIDC_ADMIN_GROUP: admins

        #OIDC_AUTH_ENABLED: true
  dataFrom:
    - extract:
        key: ${CLUSTER}/mealie
    - extract:
        key: ${CLUSTER}/openid/mealie
    - extract:
        key: ${CLUSTER}/pg-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
