---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mealie:
        replicas: ${REPLICAS:=1}
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.2.1@sha256:322369a5b748eddb091417e708f0667d21994e6119278d1b8c509900ba41e54b
            env:
              TZ: ${CLUSTER_TIMEZONE}
              ALLOW_SIGNUP: "false"
              BASE_URL: https://home-mealie.${SECRET_DOMAIN}
              PGID: 1000
              PUID: 1000
              API_DOCS: false
              ALLOW_PASSWORD_LOGIN: false
              #TOKEN_TIME: "24" # hours
            envFrom:
              - secretRef:
                  name: *app

            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 512M

    #serviceMonitor:
    #  app:
    #    serviceName: *app
    #    endpoints:
    #      - port: http
    #        scheme: http
    #        path: /metrics
    #        interval: 1m
    #        scrapeTimeout: 10s

    service:
      app:
        controller: *app
        ports:
          http:
            port: 9000
    #ingress:
    #  app:
    #    enabled: true
    #    className: ${INGRESSCLASS}
    #    annotations:
    #      gethomepage.dev/enabled: "true"
    #      gethomepage.dev/description: "Recipe management for the modern household."
    #      gethomepage.dev/group: Home
    #      gethomepage.dev/name: "Mealie"
    #      gethomepage.dev/icon: mealie.png
    #      gethomepage.dev/pod-selector: >-
    #        app.kubernetes.io/name in (mealie)
    #      gethomepage.dev/href: https://home-mealie.${SECRET_DOMAIN}
    #      gethomepage.dev/widget.type: mealie
    #      gethomepage.dev/widget.url: http://mealie.self-hosted:9000
    #      gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_MEALIE_API_KEY}}`}}"
    #      gethomepage.dev/widget.version: "2"
    #      gethomepage.dev/widget.fields: '["recipes", "users", "categories", "tags"]'
    #    hosts:
    #      - host: &host "home-mealie.${SECRET_DOMAIN}"
    #        paths:
    #          - path: /
    #            service:
    #              identifier: app
    #              port: http
    #    tls:
    #      - hosts:
    #        - *host
    route:
      app:
        hostnames:
          - "home-mealie.${SECRET_DOMAIN}"
        parentRefs:
          - name: base
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: 9000
        #annotations:
        #  gethomepage.dev/enabled: "true"
        #  gethomepage.dev/description: "Recipe management for the modern household."
        #  gethomepage.dev/group: Home
        #  gethomepage.dev/name: "Mealie"
        #  gethomepage.dev/icon: mealie.png
        #  #gethomepage.dev/pod-selector: >-
        #  #  app.kubernetes.io/name in (mealie)
        #  #gethomepage.dev/href: https://home-mealie.${SECRET_DOMAIN}
        #  gethomepage.dev/widget.type: mealie
        #  gethomepage.dev/widget.url: http://{{ .Release.Name }}.{{ .Release.Namespace }}:9000
        #  gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_MEALIE_API_KEY}}`}}"
        #  gethomepage.dev/widget.version: "2"
        #  gethomepage.dev/widget.fields: '["recipes", "users", "categories", "tags"]'

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: *app
        globalMounts:
          - path: "/app/data"
