---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mariadb-backup-secret
    template:
      data:
        MARIADB_HOST: "mariadb.database"
        MARIADB_USER: "{{ .MYSQL_ROOT_USER }}"
        MARIADB_PASSWORD: "{{ .MYSQL_ROOT_PASSWORD }}"
        MARIADB_PORT: "3306"
  dataFrom:
    - extract:
        key: ${CLUSTER}/mariadb
