---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-backup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      cnpg-backup:
        type: cronjob
        cronjob:
          schedule: "@daily"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/sstr-dev/backup-local
              tag: 18@sha256:c75a3a9f178d454f4d8d7ad1970fdfd7e41d22266bc3425885cf61d1376ba7bb
            command: ["/bin/bash", "/backup.sh"]
            env:
              TZ: ${CLUSTER_TIMEZONE}
              EXCLUDE_DBS: app
              DB_TYPE: mariadb
              MARIADB_EXTRA_OPTS: "--single-transaction --quick --routines --events --triggers --hex-blob --add-drop-table"
              BACKUP_DIR: /backups/database/mariadb
              BACKUP_KEEP_DAYS: "7"
              BACKUP_KEEP_WEEKS: "4"
              BACKUP_KEEP_MONTHS: "6"
              BACKUP_LATEST_TYPE: none
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 99
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      nas:
        type: nfs
        server: nas.main.internal
        path: /mnt/user/main-backup
        globalMounts:
          - path: /backups
