---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
components:
  - ../../../components/common
  - ../../../vars/casa
resources:
  - ./dragonfly-llm-cluster.yaml
  - ./searxng.yaml
  - ./postgres-llm-cluster.yaml
  - ./open-webui.yaml
  # - ./paperless-ai.yaml
