# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless-ai
  namespace: &namespace llm
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/llm/paperless-ai
  components:
    - ../../../../components/vol
  postBuild:
    substitute:
      APP: *app
      # APP_UID: "1000"
      # APP_GID: "1000"
      VOL_CAPACITY: 5Gi
      VOL_STORAGECLASS: sc-standard
      VOL_ACCESSMODES: ReadWriteMany
      VOL_RESOURCEPOLICY: keep
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: external-secrets
      namespace: security
    - name: paperless
      namespace: self-hosted
  prune: true
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
