---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 3d-print
components:
  - ../../../components/common
  - ../../../vars/casa
resources:
  - ./spoolman.yaml

