---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres17-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgres17-backup-secret
    template:
      data:
        POSTGRES_HOST: "{{ .POSTGRES17_HOST }}"
        POSTGRES_USER: "{{ .POSTGRES17_SUPER_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES17_SUPER_PASS }}"
        POSTGRES_PORT: "5432"
  dataFrom:
    - extract:
        key: ${CLUSTER}/nas-backup
