---
# template: domain, domainusecase
# DOMAIN, DOMAINUC
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ${DOMAINUC}-tls
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: "${DOMAINUC}-tls"
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: shared/certificates/${DOMAINUC}-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: shared/certificates/${DOMAINUC}-tls
          property: *key

