---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: headlamp-secret
    template:
      data:
        ## OIDC
        OIDC_CLIENT_ID: "{{ .HEADLAMP_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .HEADLAMP_CLIENT_SECRET }}"
        OIDC_ISSUER_URL: "{{ .HEADLAMP_OIDC_ISSUER }}"
        OIDC_SCOPES: "openid email profile"
  dataFrom:
    - extract:
        key: ${CLUSTER}/headlamp
