---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubeblocks-csi-s3
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-s3
      version: 0.31.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: kubeblocks
#---
## yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#  name: &app kubeblocks-csi-driver-nfs
#spec:
#  interval: 1h
#  chart:
#    spec:
#      chart: csi-driver-nfs
#      interval: 30m
#      sourceRef:
#        kind: HelmRepository
#        name: kubeblocks
#---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#  name: &app kubeblocks-csi-hostpath-driver
#spec:
#  interval: 1h
#  chart:
#    spec:
#      chart: csi-hostpath-driver
#      interval: 30m
#      sourceRef:
#        kind: HelmRepository
#        name: kubeblocks
#
