apiVersion: v1
kind: Secret
metadata:
    name: ns-database-secret
stringData:
    S3_SERVER: ENC[AES256_GCM,data:wbyeW6l4ICh33yhn0GO4vHrIV1hPgfg8,iv:Lab/oF5Vgjc1heM9HzTVMSAB0SwmJA/pZSSjUS/QkuY=,tag:JMbot9bbMKYuCbH0ii07wA==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T19:54:30Z"
    mac: ENC[AES256_GCM,data:z74Ou2hoiAvQf/4atL4OKF7YV8wVLSK6PiYMXa1rdBb1goyegWa5KhPdT70PLpvlkj9wL3z00pRAhlLlaHtXgCyuAF+TAmb/0fJk9n0u6yxpvrGfOqYKXAdjZdL7ft7ejcdjIjxRVHPZznNW/csktowM0uWmkKGnBJBwnYvOac0=,iv:scldeGxRwee0XRN9WC0WIpNkvYYUP+TPLun9vTWTRNU=,tag:FWQYV0BRCQHOFl/JsIc9uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
