---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  WORKSTATION_RESOURCES_DIR: "{{.ROOT_DIR}}/.taskfiles/Workstation/resources"

tasks:
  direnv:
    desc: Run direnv hooks
    cmd: direnv allow .
    status:
      - "[[ $(direnv status --json | jq '.state.foundRC.allowed') == 0 ]]"
      - "[[ $(direnv status --json | jq '.state.loadedRC.allowed') == 0 ]]"
  venv:
    desc: Set up virtual environment
    cmds:
      - "{{.PYTHON_BIN}} -m venv {{.VIRTUAL_ENV}}"
      - '{{.VIRTUAL_ENV}}/bin/python3 -m pip install --upgrade pip setuptools wheel'
      - '{{.VIRTUAL_ENV}}/bin/python3 -m pip install --upgrade --requirement "{{.PIP_REQUIREMENTS_FILE}}"'
    sources:
      - "{{.PIP_REQUIREMENTS_FILE}}"
    generates:
      - "{{.VIRTUAL_ENV}}/pyvenv.cfg"
    preconditions:
      - { msg: "Missing Pip requirements file", sh: "test -f {{.PIP_REQUIREMENTS_FILE}}" }

  brew:
    desc: Install workstation dependencies with Brew
    cmds:
      - brew bundle --file {{.WORKSTATION_RESOURCES_DIR}}/Brewfile
      - |
        if helm plugin list | awk 'NR>1{print $1}' | grep -qx diff; then
          echo "helm-diff already installed"
          helm plugin update diff
        else
          helm plugin install https://github.com/databus23/helm-diff
        fi
      # - helm plugin install https://github.com/databus23/helm-diff
    sources:
      - '{{.WORKSTATION_RESOURCES_DIR}}/Brewfile'
    generates:
      - '{{.WORKSTATION_RESOURCES_DIR}}/Brewfile.lock.json'
    preconditions:
      - which brew
      - test -f {{.WORKSTATION_RESOURCES_DIR}}/Brewfile

  krew:
    desc: Set up Krew tools
    deps: [brew]
    cmds:
      - kubectl krew install cert-manager cnpg browse-pvc node-shell rook-ceph view-secret
    preconditions:
      - kubectl krew version
      - which kubectl
