---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: n8n
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        DB_TYPE: postgresdb
        DB_POSTGRESDB_DATABASE: "{{ .DB_POSTGRESDB_DATABASE }}"
        DB_POSTGRESDB_HOST: "{{ .DB_POSTGRESDB_HOST }}"
        DB_POSTGRESDB_USER: "{{ .DB_POSTGRESDB_USER }}"
        DB_POSTGRESDB_PASSWORD: "{{ .DB_POSTGRESDB_PASSWORD }}"
        DB_POSTGRESDB_PORT: "5432"

  dataFrom:
    - extract:
        key: ${CLUSTER}/n8n
