---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: authentik-referencegrants
  namespace: security
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "30m"
spec:
  inputs:
    - namespace: automation
    - namespace: database
    - namespace: download
    - namespace: external-secrets
    - namespace: self-hosted
    - namespace: media
    - namespace: network
    - namespace: observability
    - namespace: storage
  resourcesTemplate: |
    ---
    apiVersion: gateway.networking.k8s.io/v1beta1
    kind: ReferenceGrant
    metadata:
      name: allow-<< inputs.namespace >>-to-auth-services
      namespace: security
    spec:
      from:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          namespace: << inputs.namespace >>
      to:
        - group: ""
          kind: Service
