---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sstr-dev-runner
spec:
  interval: 1h
  path: ./kubernetes/apps/base/actions-runner-system/actions-runner-controller/runners/organization
  prune: true
  dependsOn:
    - name: actions-runner-controller-runners-base
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
    # idea for vars:
    # gHorg: faiph-dev
    # APP: faiph-dev
    # AUTHKEY: faiph_dev = faiph_dev_github_app_id
    # runnerScaleSetName: arc-runner-set-${gHorg}
    # minRunners, maxRunners
      APP: *app
      CLUSTER: ${CLUSTER}
      AUTHKEY: sstr_dev
      gHorg: sstr-dev
      VOL_STORAGECLASS: local-hostpath
      VOL_CAPACITY: 2Gi
  wait: false




