---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-adguard-home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: external-dns-adguard-home
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADGUARD_USER: "{{ .hass_controll_user }}"
        ADGUARD_PASSWORD: "{{.hass_controll_password }}"
        ADGUARD_URL: "{{.hass_adguard_url }}"
  dataFrom:
    #- extract:
    #    key: ${CLUSTER}/adguard
    - extract:
        key: ${CLUSTER}/hass
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hass_$1"
