---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-oidc
spec:
  oidc:
    redirectURL: "https://${GATUS_SUBDOMAIN:-${SUBDOMAIN:-${APP}}}.${SECRET_MAIN_DOMAIN_NAME}/oauth2/callback"
