---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: multi-domain
spec:
  secretName: "${DOMAINUC}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${CERT_MAIN_DOMAIN}"
  dnsNames: ["${CERT_DOMAIN}", "*.${CERT_DOMAIN}", "*.${CERT_MAIN_DOMAIN}", "${CERT_DEV_DOMAIN}", "*.${CERT_DEV_DOMAIN}", "${CERT_GAME_DOMAIN}", "*.${CERT_GAME_DOMAIN}"]
  #secretTemplate:
  #  annotations:
  #    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  #    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "network"
  #    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
