---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
    template:
      data:
        # App
        SECRET_KEY: "{{ .SECRET_KEY }}"
        # postgres
        POSTGRES_HOST: postgres-cluster-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: tandoor
        POSTGRES_PASSWORD: "{{ .sql_tandoor }}"
        POSTGRES_DB: tandoor
        DB_ENGINE: django.db.backends.postgresql_psycopg2
        # Email
        EMAIL_HOST: "smtp-relay.default.svc.cluster.local"
        EMAIL_PORT: "25"
        EMAIL_USE_SSL: "0"
        DEFAULT_FROM_EMAIL: "Recipes <${SECRET_SMTP_FROM_FULL}>"
        ACCOUNT_EMAIL_SUBJECT_PREFIX: "[Recipes]"
        # OpenId Connect
        SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
        SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Casa SSO",
                        "client_id": "{{ .client_id }}",
                        "secret": "{{ .client_secret }}",
                        "settings": {
                            "server_url": "{{ .openid_config }}"
                        }
                    }
                ]
            }
          }
  dataFrom:
    - extract:
        key: ${CLUSTER}/tandoor
    - extract:
        key: ${CLUSTER}/openid/recipes
    - extract:
        key: ${CLUSTER}/pg-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
