---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nut-upsd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      nut-upsd:
        containers:
          app:
            image:
              repository: docker.io/instantlinux/nut-upsd
              tag: 2.8.2-r0
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
            env:
              TZ: ${CLUSTER_TIMEZONE}
              DRIVER: "usbhid-ups"
              DESCRIPTION: "Back-UPS BX1200MI"
              SERIAL: "9B2518A00511"
            envFrom:
              - secretRef:
                  name: *app
        pod:
          nodeSelector:
            ups.feature.node.kubernetes.io/apc: "true"
          tolerations:
            - key: "homelab.k8s.io/type"
              operator: "Equal"
              value: "vm"
              effect: "NoExecute"
    service:
      app:
        type: LoadBalancer
        controller: *app
        annotations:
          kube-vip.io/pool: iot
          kube-vip.io/serviceInterface: iot
          kube-vip.io/loadbalancerIPs: ${LB_V4_NUT_IOT}
        ports:
          http:
            port: 3493
            protocol: TCP
