---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: sonarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SONARR__AUTH__APIKEY: "{{ .api_key }}"
        SONARR__POSTGRES__HOST: postgres-cluster-rw.database.svc.cluster.local
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: "sonarr"
        SONARR__POSTGRES__PASSWORD: "{{ .sql_sonarr }}"
        SONARR__POSTGRES__MAINDB: sonarr
  dataFrom:
    - extract:
        key: ${CLUSTER}/sonarr
    - extract:
        key: ${CLUSTER}/pg-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
