---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  path: ./kubernetes/apps/base/database/cloudnative-pg/operator
  prune: true
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudnative-pg
      namespace: database
  postBuild:
    substitute:
      CLUSTER: ${CLUSTER}
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-barman-cloud
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: cloudnative-pg
  path: ./kubernetes/apps/base/database/cloudnative-pg/barman-cloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/plugin-barman-cloud-sidecar
      SIDECAR_IMAGE_VERSION: v0.11.0
      # docker pull ghcr.io/cloudnative-pg/plugin-barman-cloud-sidecar:v0.11.0@sha256:fc8a908f639b295296b7523e6ecc38945167d5d2d8734e588ea4d53a6511851a
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
spec:
  interval: 1h
  path: ./kubernetes/apps/${CLUSTER}/database/cloudnative-pg/cluster
  postBuild:
    substitute:
      LB_SERVICE_IP: 10.0.60.56
      LB_SERVICE_SEGMENT: servers
      CNPG_STORAGECLASS: local-hostpath
      CNPG_REPLICAS: '3'
      CNPG_SIZE: 5Gi
      CNPG_REQUESTS_MEMORY: 1Gi
      CNPG_LIMITS_MEMORY: 2Gi
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: ns-database-secret
  dependsOn:
    - name: cloudnative-pg
    - name: cloudnative-pg-barman-cloud
    - name: openebs
      namespace: storage
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-backup
spec:
  dependsOn:
    - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/${CLUSTER}/database/cloudnative-pg/cluster/backup
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
