---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../../components/common
  - ../../../vars/main/namespaces/database
replacements:
  - path: ../../../components/replacements/ks.yaml
resources:
  - ./cloudnative-pg.yaml
  - ./dragonfly.yaml
# TODO: Services: cloudnative-pg (local, s3, + ferretDB?)
# optional: mariadb, mongodb, kafka
