---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-wireless
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-wireless",
      "plugins": [
        {
          "type": "macvlan",
          "master": "iot",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "${SECRET_MULTUS_IOT_NET}/24",
                "gw": "${SECRET_MULTUS_IOT_GTW_IP}"
              }
            ],
            "gateway": [
              "${SECRET_MULTUS_IOT_GTW_IP}"
            ],
            "capabilities": { "mac": true }
          }
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }
