---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../../components/common
  - ../../../vars/casa
resources:
  - ./postgres-observability-cluster.yaml
  - ./gatus.yaml
  - ./grafana.yaml
  - ./kube-prometheus-stack.yaml
  - ./config/kube-prometheus-stack
  # Exporters
  - ./exporters

