---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2025.6.3
  url: oci://ghcr.io/goauthentik/helm-charts/authentik
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: authentik
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: *app
      deploymentStrategy:
        type: RollingUpdate
      #env:
      #  - name: AUTHENTIK_POSTGRESQL__NAME
      #    value: *app
      #  - name: AUTHENTIK_POSTGRESQL__HOST
      #    value: pg-cluster-postgresql.database.svc.cluster.local
      #  - name: AUTHENTIK_POSTGRESQL__USER
      #    value: *app
      #  - name: AUTHENTIK_POSTGRESQL__USE_PGBOUNCER
      #    value: "false"
      #  - name: AUTHENTIK_POSTGRESQL__SSLMODE
      #    value: require
      envFrom:
        - secretRef:
            name: *app
    authentik:
      #postgresql:
      #  host: pg-cluster-postgresql.database.svc.cluster.local
      #  user: file:///postgres-creds/username
      #  password: file:///postgres-creds/password
      #email:
      #  from: "${SECRET_SMTP_FROM_FULL}"
      #  host: smtp-relay.default.svc.cluster.local
      #  port: 25
      #  use_tls: false
      #redis:
      #  host: dragonfly-authentik
      disable_update_check: true
      disable_startup_analytics: true
    server:
      autoscaling: &autoscaling
        enabled: true
        minReplicas: 1
        maxReplicas: 5
        targetCPUUtilizationPercentage: 60
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 300
          scaleDown:
            stabilizationWindowSeconds: 300
      resources:
        requests:
          cpu: 300m
        limits:
          memory: 1Gi
      metrics:
         # -- deploy metrics service
        enabled: true
        serviceMonitor:
          # -- enable a prometheus ServiceMonitor
          enabled: true
      # -- Additional volumes to the authentik server pod
      volumes:
        - name: authentik-templates
          persistentVolumeClaim:
            claimName: authentik-custom-templates
        - name: authentik-media
          persistentVolumeClaim:
            claimName: authentik-media
      # -- Additional volumeMounts to the authentik server main container
      volumeMounts:
        - name: authentik-templates
          mountPath: /templates
        - name: authentik-media
          mountPath: /media
      #ingress:
      #  enabled: true
      #  ingressClassName: ${SSO_INGRESSCLASS}
      #  annotations:
      #    gethomepage.dev/enabled: "true"
      #    gethomepage.dev/icon: authentik.png
      #    gethomepage.dev/name: Authentik
      #    gethomepage.dev/group: Infrastructure
      #    gethomepage.dev/app: authentik
      #    gethomepage.dev/description: OIDC User Management
      #    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      #    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      #    nginx.org/websocket-services: authentik
      #    nginx.ingress.kubernetes.io/enable-global-auth: "false"
      #    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      #    #nginx.ingress.kubernetes.io/server-snippet: |
      #    #  location ~* /if/admin {
      #    #    allow ${LOCAL_CIDR_1};
      #    #    allow ${LOCAL_CIDR_2};
      #    #    deny all;
      #    #  }
      #  hosts:
      #    - &host "${SECRET_SSO_DOMAIN}"
      #  tls:
      #    - hosts:
      #        - *host

    worker:
      autoscaling: *autoscaling
      resources:
        requests:
          cpu: 300m
        limits:
          memory: 1Gi

