---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik
  #annotations:
  #  gethomepage.dev/enabled: 'true'
  #  gethomepage.dev/icon: authentik.png
  #  gethomepage.dev/name: Authentik
  #  gethomepage.dev/group: Infrastructure
  #  gethomepage.dev/app: authentik
  #  #gethomepage.dev/description: OIDC User Management
  #  #gethomepage.dev/widget.type: authentik
  #  #gethomepage.dev/widget.url: http://authentik-server.sso.svc.cluster.local
  #  #gethomepage.dev/widget.key: '{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}'
spec:
  hostnames:
    - ${SECRET_SSO_DOMAIN}
  parentRefs:
    - name: base
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: authentik-server
          port: 80
