---
# yaml-language-server: $schema=https://schemas.sstr.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  values:
    runnerScaleSetName: arc-runner-set-${gHorg}
    githubConfigUrl: https://github.com/${gHorg}
    githubConfigSecret: ${APP}-secret
    minRunners: ${minRunners:=1}
    maxRunners: ${maxRunners:=2} #Double total nodes
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["${VOL_ACCESSMODES:-ReadWriteOnce}"]
        storageClassName: "${VOL_STORAGECLASS:=local-hostpath}"
        resources:
          requests:
            storage: "${VOL_CAPACITY:=5Gi}"

    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.333.1@sha256:1a7726bcaeba4e46fe07fe98e1805b4df78618a71e67758f932862b929f852d4
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
            volumeMounts:
              - mountPath: /var/run/secrets/talos.dev
                name: talos
                readOnly: true
        serviceAccountName: ${APP}
        volumes:
          - name: talos
            secret:
              secretName: ${APP}
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
