---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  CLUSTER_TIMEZONE: "Europe/Berlin"
  CLUSTER: registry

  SERVICE_CIDR: "10.43.0.0/16"

  #LB_SERVICE_INTERFACE: services
  #LB_SERVICE_POOL: services
  LB_INTERNAL_INTERFACE: eth0


  #GATEWAY_INT_IPV4:
  #GATEWAY_EXT_IPV4:

  DOMAIN: registry.lokis-casa.internal

