---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-recs
  labels:
    app.kubernetes.io/name: scrypted-recs
    app.kubernetes.io/instance: scrypted
spec:
  storageClassName: sc-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
