---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ingress-nginx-repo
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/network/nginx
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app internal-ingress-nginx
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/network/nginx/internal
  postBuild:
    substitute:
      APP: *app
      REPLICAS: "2"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  dependsOn:
    - name: ingress-nginx-repo
    - name: internal-cluster-certificate
      namespace: default
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
#---
## yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &app iot-ingress-nginx
#spec:
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *app
#  interval: 1h
#  path: ./kubernetes/apps/base/network/nginx/iot
#  postBuild:
#    substitute:
#      APP: *app
#      REPLICAS: "2"
#    substituteFrom:
#      - kind: ConfigMap
#        name: cluster-settings
#  prune: true
#  dependsOn:
#    - name: internal-ingress-nginx
#  retryInterval: 2m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  targetNamespace: network
#  timeout: 5m
#  wait: false
#---
## yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &app iot-base-ingress-nginx
#spec:
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *app
#  interval: 1h
#  path: ./kubernetes/apps/base/network/nginx/iot-base
#  postBuild:
#    substitute:
#      APP: *app
#      REPLICAS: "2"
#    substituteFrom:
#      - kind: ConfigMap
#        name: cluster-settings
#  prune: true
#  dependsOn:
#    - name: iot-ingress-nginx
#  retryInterval: 2m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  targetNamespace: network
#  timeout: 5m
#  wait: false
#---
## yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &app iot-dev-ingress-nginx
#spec:
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *app
#  interval: 1h
#  path: ./kubernetes/apps/base/network/nginx/iot-dev
#  postBuild:
#    substitute:
#      APP: *app
#      REPLICAS: "2"
#    substituteFrom:
#      - kind: ConfigMap
#        name: cluster-settings
#  prune: true
#  dependsOn:
#    - name: iot-ingress-nginx
#  retryInterval: 2m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  targetNamespace: network
#  timeout: 5m
#  wait: false
#
