---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app test2
spec:
  components:
    - ../../../../components/volsync
    - ../../../../components/volmigrate/nfs
#  path: ./kubernetes/migration/common
#  components:
#    - ../../../../components/volsync
#    - ../../../../components/volmigrate/nfs
  interval: 1h
  #path: ./kubernetes/apps/${CLUSTER}/default/test2
  path: ./kubernetes/migration/common
  postBuild:
    substitute:
      APP: *app
      CLUSTER: ${CLUSTER}
      VOLSYNC_CAPACITY: 1Gi
      BOOTSTRAP_DEBUG_SLEEP: "300"
      #VOLSYNC_STORAGECLASS: longhorn-volsync
      #VOLSYNC_SNAPSHOTCLASS: longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false


