---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ADMIN_TOKEN: "{{ .VAULTWARDEN_ADMIN_TOKEN }}"
        # SSO
        SSO_CLIENT_ID: "{{ .VAULTWARDEN_CLIENT_ID }}"
        SSO_CLIENT_SECRET: "{{ .VAULTWARDEN_CLIENT_SECRET }}"
        SSO_AUTHORITY: "{{ .VAULTWARDEN_OIDC_ISSUER }}"

        # Database
        DATABASE_URL: |-
          postgres://{{ .VAULTWARDEN_POSTGRES_USER }}:{{ .VAULTWARDEN_POSTGRES_PASSWORD }}@{{ .VAULTWARDEN_POSTGRES_HOST }}/{{ .VAULTWARDEN_POSTGRES_DB }}
  dataFrom:
    - extract:
        key: ${CLUSTER}/vaultwarden


