---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: downloads-gateway-webhook-selfsign
  labels:
    app.kubernetes.io/name: downloads-gateway
    app.kubernetes.io/instance: downloads-gateway
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downloads-gateway-webhook-ca
  labels:
    app.kubernetes.io/name: downloads-gateway
    app.kubernetes.io/instance: downloads-gateway
spec:
  secretName: downloads-gateway-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: downloads-gateway-webhook-selfsign
    kind: Issuer
  commonName: "ca.downloads-gateway.cert-manager"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: downloads-gateway-webhook-ca
  labels:
    app.kubernetes.io/name: downloads-gateway
    app.kubernetes.io/instance: downloads-gateway
spec:
  ca:
    secretName: downloads-gateway-webhook-ca
---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downloads-gateway-webhook-tls
  labels:
    app.kubernetes.io/name: downloads-gateway
    app.kubernetes.io/instance: downloads-gateway
spec:
  secretName: downloads-gateway-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: downloads-gateway-webhook-ca
    kind: Issuer
  dnsNames:
    - downloads-gateway-webhook
    - downloads-gateway-webhook.vpn-gateway
    - downloads-gateway-webhook.vpn-gateway.svc
