---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app downloads-gateway-webhook
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      downloads-gateway-webhook:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/angelnu/gateway-admision-controller
              tag: v3.12.0@sha256:6f6ab596afd5fef0ca4648eadfb21cd37ba86fa5afa8b85edcc072976a61fbed
            args:
              - --webhook-listen-address=:443
              - --gateway=downloads-gateway.vpn-gateway.svc.cluster.local
              - --DNS=172.16.1.1
              - --configmapName=downloads-gateway
              - --setGatewayLabel=setDownloadGateway
              - --setGatewayAnnotation=setDownloadGateway
              # Static
              - --tls-cert-file-path=/tls/tls.crt
              - --tls-key-file-path=/tls/tls.key
              - --DNSPolicy=None
              # Init container
              - --initImage=ghcr.io/angelnu/pod-gateway:v1.13.0
              - --initImagePullPol=IfNotPresent
              - --initCmd=/bin/client_init.sh
              - --initMountPoint=/config
              # Sidecar container
              - --sidecarImage=ghcr.io/angelnu/pod-gateway:v1.13.0
              - --sidecarImagePullPol=IfNotPresent
              - --sidecarCmd=/bin/client_sidecar.sh
              - --sidecarMountPoint=/config
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 50Mi
            probes:
              readiness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /wh/health
                    port: 443
                    scheme: HTTPS
                  initialDelaySeconds: 1
                  timeoutSeconds: 10
                  periodSeconds: 10
                  successThreshold: 1
                  failureThreshold: 5
              liveness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /wh/health
                    port: 443
                    scheme: HTTPS
                  timeoutSeconds: 1
                  periodSeconds: 1
                  successThreshold: 1
                  failureThreshold: 30
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        controller: *app
        ports:
          http:
            port: 443
    persistence:
      config:
        type: secret
        name: downloads-gateway-webhook-tls
        globalMounts:
          - path: /tls
            readOnly: true
