---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: forgejo-secret
    template:
      data:
        # App
        username: "{{ .FORGEJO_ADMIN }}"
        email: "{{ .FORGEJO_ADMIN_EMAIL }}"
        password: "{{ .FORGEJO_ADMIN_PASSWORD }}"
        FORGEJO_SECRET_KEY: "{{ .FORGEJO_SECRET_KEY }}"
        FORGEJO_INTERNAL_TOKEN: "{{ .FORGEJO_INTERNAL_TOKEN }}"
        REDIS_URL: |-
          redis://:{{ .DRAGONFLY_PASSWORD }}@dragonfly.database.svc.cluster.local:6379/8
        # S3
        #FORGEJO_AWS_ACCESS_KEY_ID: "{{ .FORGEJO_AWS_ACCESS_KEY_ID }}"
        #FORGEJO_AWS_SECRET_ACCESS_KEY: "{{ .FORGEJO_AWS_SECRET_ACCESS_KEY }}"
        # OIDC
        key: "{{ .FORGEJO_CLIENT_ID }}"
        secret: "{{ .FORGEJO_CLIENT_SECRET }}"
        # Database
        POSTGRES_USERNAME: "{{ .FORGEJO_POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .FORGEJO_POSTGRES_PASSWORD }}"
        POSTGRES_DB: "{{ .FORGEJO_POSTGRES_DB }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/forgejo
    - extract:
        key: ${CLUSTER}/dragonfly
