---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "forgejo-data"
spec:
  accessModes: ["${VOL_ACCESSMODES:-ReadWriteOnce}"]
  resources:
    requests:
      storage: "${VOL_CAPACITY:=5Gi}"
  storageClassName: "${VOL_STORAGECLASS:=longhorn}"

