---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-gateway
  namespace: network # Required for Renovate lookups
spec:
  interval: 1h
  url: https://ori-edge.github.io/k8s_gateway
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s-gateway
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: network
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    domain: "${K8SGTWDOMAINS}" # also a list of domains
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        kube-vip.io/pool: default
        kube-vip.io/loadbalancerIPs: ${LB_V4_K8S_GATEWAY}
        # kube-vip.io/pool: iot
        # kube-vip.io/serviceInterface: iot
      externalTrafficPolicy: Cluster
    watchedResources: ["HTTPRoute", "Service"]
