---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app it-tools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      it-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
            fsGroup: 100
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/sstr-dev/it-tools
              tag: 2026.7.11@sha256:b3d675cdd5ee67d60c2b2a67c343af8bbde03380f9eeca7afa9895007add7223
            env:
              TZ: ${CLUSTER_TIMEZONE}
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DEV_DOMAIN}"
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: ${GATEWAY:=dev}
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: Dev
        #annotations:
        #  gethomepage.dev/enabled: "true"
        #  gethomepage.dev/description: Swiss army knife for IT
        #  gethomepage.dev/group: Home
        #  gethomepage.dev/icon: it-tools.svg
        #  gethomepage.dev/name: IT-Tools
    persistence:
      tmp:
        type: emptyDir
        advancedMounts:
          it-tools:
            app:
              - path: /tmp
                subPath: tmp
