---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  #- ./manual-ingress.yaml
  - ./pvc/registry.yaml
  - ./pvc/jobservice.yaml
  - ./pvc/jobservice-scandata.yaml
  - ./pvc/redis.yaml
  - ./pvc/trivy.yaml
  - ./httproute.yaml
