---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: devices-v4
spec:
  module: icmp
  metricRelabelings:
    - action: labeldrop
      regex: (pod)
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        ## Network
        - ${SECRET_FRITZ_IP}
        - ${SECRET_OPNSENSE_IP}
        - ${SECRET_GTW_IP}

