---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: services
spec:
  module: http_2xx
  metricRelabelings:
    - action: labeldrop
      regex: (pod)
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        #- "https://adguard.${SECRET_OFFSITE_DOMAIN}"
        #- "https://bilder.${SECRET_OFFSITE_DOMAIN}"
        #- "https://status.${SECRET_PUBLIC_DOMAIN}"
        - "http://${SECRET_S3_BACKUP_STORAGE_IP}:9001"
