---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: 25.8.4
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator

