---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name mariadb-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: mariadb-operator
      version: 25.10.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/mariadb-operator/mariadb-operator
      pullPolicy: IfNotPresent
      tag: 25.8.4
    ha:
      enabled: true
      replicas: 3
    resources:
      requests:
        cpu: 50m
        memory: 128M
      limits:
        memory: 1024M
    webhook:
      ha:
        enabled: true
        replicas: 3
      cert:
        certManager:
          enabled: true
      port: 9443
      serviceMonitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 25s
      resources:
        requests:
          cpu: 50m
          memory: 128M
        limits:
          memory: 512M
    certController:
      enabled: false
    metrics:
      # -- Enable operator internal metrics. Prometheus must be installed in the cluster
      enabled: false
