{
 "title": "Proxmox Cluster",
 "description": "Proxmox Virtual Environment Dashboard",
 "tags": [
  "Proxmox",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(pve_node_info, instance)"
    }
   },
   { "name": "node", "label": "node", "query": { "query": "label_values(id)" } },
   { "name": "Filters" },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{instance=\"$instance\", node=~\"$${node:text}|.*($${node})\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"$instance\"} and on (id, instance) pve_guest_info{node=~\"$${node:text}|.*($${node})\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\"} and on (id, instance) pve_guest_info{node=~\"$${node:text}|.*($${node})\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{node=~\"$${node:text}|.*($${node})\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"$instance\",template!=\"1\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info{node=~\"$${node:text}|.*($${node})\"} and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{node=~\"$${node:text}|.*($${node})\"})"
    },
    {
     "expr": "sum by (id) (rate(pve_disk_read_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) and on(id, instance) pve_guest_info{node=~\"$${node:text}|.*($${node})\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\", id=~\"$node\"} and on(id) pve_node_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Current CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\", id=~\"$node\"}  and on(id) pve_node_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_limit{instance=\"$instance\", id=~\"$node\"} and on(id) pve_node_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\", id=~\"$node\"} / pve_memory_size_bytes and on(id) pve_node_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit) * on(id, instance) group_left(name, type) pve_guest_info{node=~\"$${node:text}|.*($${node})\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info{node=~\"$${node:text}|.*($${node})\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\", id=~\"storage/.+\"} / pve_disk_size_bytes * on (id, instance) group_left(storage) pve_storage_info{node=~\"$${node:text}|.*($${node})\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{instance=\"$instance\", id=~\"storage/.+\"} * on (id, instance) group_left(storage) pve_storage_info{node=~\"$${node:text}|.*($${node})\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name, type) pve_guest_info{node=~\"$${node:text}|.*($${node})\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} RECV ({{type}})"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m])* on(id, instance) group_left(name, type) pve_guest_info{node=~\"$${node:text}|.*($${node})\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} SEND ({{type}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name, type) pve_guest_info{node=~\"$${node:text}|.*($${node})\"}) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  }
 ]
}