endpoints:
  - name: "${APP}"
    group: "${GATUS_GROUP:=guarded}"
    url: 1.1.1.1
    interval: "${GATUS_INTERVAL:=1m}"
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.${CLUSTER_DOMAIN}"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover
