---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: readarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        READARR__AUTH__APIKEY: "{{ .api_key }}"
        READARR__POSTGRES_HOST: postgres-cluster-rw.database.svc.cluster.local
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: "readarr"
        READARR__POSTGRES__PASSWORD: "{{ .sql_readarr }}"
        READARR__POSTGRES_MAIN_DB: readarr
  dataFrom:
    - extract:
        key: ${CLUSTER}/readarr
    - extract:
        key: ${CLUSTER}/pg-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
