---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvdp-charts
spec:
  interval: 30m
  url: https://nvidia.github.io/k8s-device-plugin
  timeout: 3m
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.18.0
      sourceRef:
        kind: HelmRepository
        name: nvdp-charts
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runtimeClassName: nvidia
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    nodeSelector:
      gpu: "true"
    affinity: []
    #config:
    #  map:
    #    default: |-
    #      version: v1
    #      flags:
    #        migStrategy: none
    #      sharing:
    #        timeSlicing:
    #          renameByDefault: false
    #          failRequestsGreaterThanOne: false
    #          resources:
    #            - name: nvidia.com/gpu
    #              replicas: 6
