apiVersion: v1
kind: Secret
metadata:
    name: cert-base-secret
stringData:
    DOMAIN: ENC[AES256_GCM,data:VolQOzz7C9UJkg==,iv:mWIWQDD7TUq9aIWxYWFIuRvlQaHwIGdANg4K/d0SCU0=,tag:Qy6ExEpXIJg013/7mtGP1A==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T15:22:38Z"
    mac: ENC[AES256_GCM,data:atXcAkmVVHplO1tN4LjIg30oxdMJSQbpMKgCQSoVThEkPxzpfcqReXkj4DJDxntk86boTtwCYYXxheXC7jglnPFADWpoARjrXjl8OrSWE4xdK+mfl+05lxwlSkY4iOB+VmUSO+n657kd52Fn3TyrcfsCEhwYnzlrI+x3N/Gghvk=,iv:ahTMw+X0Hqeo20ZY3RLg4ZQCThtPsHE97FWjbx8DgBQ=,tag:cP9weJA9kZCEYBLktIiqjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
