apiVersion: v1
kind: Secret
metadata:
    name: cert-dev-secret
stringData:
    DOMAIN: ENC[AES256_GCM,data:lIkFc+Qo7K8=,iv:BkFfCfd8tvUVdKqu1kaHY6maqOa/B6iUyLDbv/IrD5c=,tag:ijI6YMy17fn2FE4OaNHNDg==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T15:23:07Z"
    mac: ENC[AES256_GCM,data:3CTjSq7yhMzcFJS+DSA3NGrGh5da6nVD1Z8bIVTonzcd/tGPn2Ml3cy5WM0nfQlGChfnS8KuC1I4rdgvckQMK51A/Ce1vOGwpMw7R0E4j+wyB+Sb5ioFQ1B8dqS1NstoI/hPz4H3wljEOz6hFryEVtBKJhfRNJkx3uFQdvyg+mQ=,iv:BZHe4kOYpU3UyTIh/XanDrL73mrQpFx4wqxCi66+avo=,tag:S/4ep/MunRVz55IFZ4XHJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
