apiVersion: v1
kind: Secret
metadata:
    name: cert-main-secret
stringData:
    DOMAIN: ENC[AES256_GCM,data:koh6oCL2qUwO7bGcPJva,iv:+lIa11vTwt7pSAa/sKxCZYVZZXwHgdLdwkU8P3pgE70=,tag:Y/kX/sNWaTAII5hlWsDddg==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T15:12:07Z"
    mac: ENC[AES256_GCM,data:hh7kEH9sJeXUY4R9LhxVNNIODLYuFynB80lnwN5HEJqN8glqfVzVz/CZqg1kldS6xtaYPz540Rz/GH4497BhET7W18NnBi9p2xj25/vGocHQ2b93VhV69HS7pHVNZrx+bkrtDGmuoViidLrN4hpQXXXV1YboKq5EO6R+mmM6Bmw=,iv:BTGhMTqr8rBwwS5Sk5g+ZA6j5TsR8LMK8A7CRs+8BxM=,tag:BLqPWDrzRecioyKu9CMeBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
