apiVersion: v1
kind: Secret
metadata:
    name: cert-game-secret
stringData:
    DOMAIN: ENC[AES256_GCM,data:h4s+6fMf4XU=,iv:t2GsjyWvyeD+QU7z582EREKuE9YIsoG4sJC8fjvDR+o=,tag:of1Wn1rwVHsylgrfzp7plQ==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T15:23:50Z"
    mac: ENC[AES256_GCM,data:NpiHd5M5gmISqU67f7mDxU60WlGjriFiIOZXe26E+lnfUzHdwK7HNcIy+FyJ1/zOZq+1071sPAO4vtv1CIQwWcHKihOBDitH7Q7YZ+6SCf/FJhe1bLcrUz75IoXw8/xREJgjW68uMK3mhQfUhjEFRFuNpA1VZfAdJdneGJNLcv8=,iv:4sGpEw1BDhXpxPT0hgefApWE3PR2L0MbNvQ3UcyBlFI=,tag:o3ebNokAfFkh2eVLihQfOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
