---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster-certificate-main
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/default/certificate/template
  postBuild:
    substitute:
      APP: *app
      DOMAINUC: main
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cert-main-secret
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: cert-manager-issuer
      namespace: cert-manager
    - name: reflector
      namespace: kube-tools
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster-certificate-base
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/default/certificate/template
  postBuild:
    substitute:
      APP: *app
      DOMAINUC: base
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cert-base-secret
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: cert-manager-issuer
      namespace: cert-manager
    - name: reflector
      namespace: kube-tools
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster-certificate-dev
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/default/certificate/template
  postBuild:
    substitute:
      APP: *app
      DOMAINUC: dev
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cert-dev-secret
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: cert-manager-issuer
      namespace: cert-manager
    - name: reflector
      namespace: kube-tools
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cluster-certificate-game
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/default/certificate/template
  postBuild:
    substitute:
      APP: *app
      DOMAINUC: game
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cert-game-secret
  prune: true
  retryInterval: 2m
  dependsOn:
    - name: cert-manager-issuer
      namespace: cert-manager
    - name: reflector
      namespace: kube-tools
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
