---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-web-automated
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  retryInterval: 2m
  path: ./kubernetes/apps/base/media/calibre-web-automated
  postBuild:
    substitute:
      APP: *app
      VOL_CAPACITY: 5Gi
      VOL_STORAGECLASS: sc-standard
      VOL_ACCESSMODES: ReadWriteMany
      VOL_RESOURCEPOLICY: keep
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  components:
    - ../../../../components/vol
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
