---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: open-webui-secret
    template:
      data:
        # App
        WEBUI_SECRET_KEY: "{{ .OPENWEBUI_SECRET_KEY }}"
        # OPENAI_API_KEY: "{{ .OPENWEBUI_OPENAI_API_KEY }}"
        # Websocket / Session Store
        REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/6?password={{ .DRAGONFLY_PASSWORD | urlquery }}"
        WEBSOCKET_REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/6?password={{ .DRAGONFLY_PASSWORD | urlquery }}"
        #REDIS_URL: |-
        #  redis://dragonfly-llm.llm.svc.cluster.local:6379/13
        #WEBSOCKET_REDIS_URL: |-
        #  redis://dragonfly-llm.llm.svc.cluster.local:6379/13
        # Database
        DATABASE_URL: |-
          postgres://{{ .OPENWEBUI_POSTGRES_USER }}:{{ .OPENWEBUI_POSTGRES_PASSWORD }}@{{ .OPENWEBUI_POSTGRES_HOST }}/{{ .OPENWEBUI_POSTGRES_DB }}
        # OIDC
        OAUTH_CLIENT_ID: "{{ .OPENWEBUI_OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPENWEBUI_OIDC_CLIENT_SECRET }}"
        OAUTH_PROVIDER_NAME: ID
        OPENID_PROVIDER_URL: "{{ .OPENWEBUI_OIDC_CONFIG }}"
        OPENID_REDIRECT_URI: "{{ .OPENWEBUI_OIDC_REDIRECT_URI }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/openwebui
    - extract:
        key: ${CLUSTER}/dragonfly
