---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publish-k8s-schemas-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: publish-k8s-schemas-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ .cloudflare_account_id }}"
        CLOUDFLARE_API_TOKEN: "{{ .cloudflare_k8s_schemas }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/cloudflare
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cloudflare_$1"
