---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publish-k8s-schemas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: publish-k8s-schemas-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ . K8S_SCHEMAS_CLOUDFLARE_ACCOUNT_ID }}"
        CLOUDFLARE_API_TOKEN: "{{ . K8S_SCHEMAS_CLOUDFLARE_API_TOKEN }}"
        LAB_ASSISTANT_TOKEN: "{{ . K8S_SCHEMAS_LAB_ASSISTANT_TOKEN }}"
        LAB_ASSISTANT_EMAIL: "{{ . K8S_SCHEMAS_LAB_ASSISTANT_EMAIL }}"
        GIT_REPO: "{{ . K8S_SCHEMAS_GIT_REPO }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/k8s-schemas
