endpoints:
  - name: "${APP}"
    group: "${GATUS_GROUP:=internal}"
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.${CLUSTER_DOMAIN}${GATUS_PATH:=/}"
    interval: "${GATUS_INTERVAL:=1m}"
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
    alerts:
      - type: pushover
