# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app change-detection
spec:
  interval: 1h
  path: ./kubernetes/apps/base/self-hosted/change-detection
  components:
    - ../../../../components/envoy/oidc/authentik/main
  postBuild:
    substitute:
      APP: *app
      APP_UPPER: CHANGE_DETECTION
      APP_SLUG: change-detection
      CLUSTER: ${CLUSTER}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
