# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app opencloud
spec:
  interval: 1h
  path: ./kubernetes/apps/base/self-hosted/opencloud
  #path: ./kubernetes/apps/base/migration/common
  components:
    - ../../../../components/volsync
    #- ../../../../components/volmigrate/nfs
  postBuild:
    substitute:
      APP: *app
      REPLICAS: "1"
      # APP_UID: "1000"
      # APP_GID: "1000"
      VOLSYNC_CAPACITY: 2Gi
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
