---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre-downloader
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: ghcr.io/calibrain/calibre-web-automated-book-downloader
              tag: 20250806@sha256:b68b3d014818fdf358f4a0655c5ba94fc6f58014e664c895f25790ac5b4d0cca
            env:
              FLASK_PORT: &port 80
              FLASK_DEBUG: false
              UID: 1000
              GID: 1000
              AA_BASE_URL: https://annas-archive.li
              INGEST_DIR: &ingest /cwa-book-ingest
              #SUPPORTED_FORMATS: epub,mobi,azw3,fb2,djvu,cbz,cbr,pdf
              BOOK_LANGUAGE: de,en
              CUSTOM_DNS: cloudflare
              USE_DOH: true
            command: # don't run startup script, since it doesn't work on a read-only fs
              - bash
              - -c
              - touch /usr/local/lib/python3.10/site-packages/seleniumbase/drivers/__init__.py && python -m app
            #probes:
            #  liveness: &probe
            #    enabled: true
            #    custom: true
            #    spec:
            #      httpGet:
            #        path: /request/api/status
            #        port: *port
            #  readiness: *probe
            #  startup: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ['ALL'] }
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      annotations:
        setDownloadGateway: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups: [65534] # nobody group, required since calibre-web-automated tries to use root on startup
        fsGroupChangePolicy: 'OnRootMismatch'

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - calibre-downloader.${SECRET_MAIN_DOMAIN_NAME}
        parentRefs:
          - name: main
            namespace: network
            sectionName: https
        rules:
          - backendRefs: [{}]

    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          # chromium needs the XDG_CONFIG_HOME created
          # because user 1000 doesn't exist, ~ = /
          - path: /.config
            subPath: config
          - path: /tmp
            subPath: tmp
          - path: /var/log/cwa-book-downloader/
            subPath: log
          - path: /app/downloaded_files
            subPath: download
          - path: /usr/local/lib/python3.10/site-packages/seleniumbase/drivers
            subPath: drivers
      ingest:
        enabled: true
        type: hostPath
        hostPath: ${SHARED_MEDIA_PATH}/cwa-book-ingest
        globalMounts:
          - path: *ingest
