---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
    template:
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
        # Admin User
        adminUser: "{{ .GRAFANA_ADMIN_USER }}"
        adminPass: "{{ .GRAFANA_ADMIN_PASS }}"
        # DB
        TESLAMATE_DB_PASSWORD: "{{ .TESLAMATE_POSTGRES_PASS }}" # from teslamate
        TESLAMATE_DB_USER: "{{ .TESLAMATE_POSTGRES_USER }}"
        # Influx
        INFLUX_GRAFANA_TOKEN: "{{ .INFLUX_GRAFANA_TOKEN }}"
        # Grafana DB
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_HOST: postgres-observability-rw.observability.svc.cluster.local:5432
        GF_DATABASE_USER: &dbUser "{{ .GRAFANA_POSTGRES_USER }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .GRAFANA_POSTGRES_PASS }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres-observability-rw.observability.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER_FLAGS: "-s"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: ${CLUSTER}/grafana
    - extract:
        key: ${CLUSTER}/teslamate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "TESLAMATE_$1"
    - extract:
        key: ${CLUSTER}/influx
      rewrite:
        - regexp:
            source: "(.*)"
            target: "INFLUX_$1"
    - extract:
        key: ${CLUSTER}/openid/grafana
    - extract:
        key: ${CLUSTER}/cloudnative-pg
