---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocsinventory
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ocsinventory
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OCS_DB_PASS: "{{ .sql_ocsinventory }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/mysql-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
