---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ocsinventory
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ocsinventory:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ocsinventory/ocsinventory-docker-image
              tag: 2.12.3
            env:
              OCS_DB_SERVER: mariadb.database.svc.cluster.local
              OCS_DB_PORT: 3306
              OCS_DB_NAME: "ocsinventory"
              OCS_DB_USER: "ocsinventory"
              OCS_SSL_ENABLED: 0
              OCS_DBI_PRINT_ERROR: 0
              TZ: ${CLUSTER_TIMEZONE}
              #APACHE_SERVER_NAME: "{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}"
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 50m
                memory: 300M
              limits:
                memory: 500M
      # ocsinventory-job
      # cron: 0 0 * * *
      # ghcr.io/sstr-dev/kubectl:1.33.3@sha256-4ab498f9ad398c572e15ccf479276e0067fcd90832a2dffb77cd634aa29cd0f0
      # cmd: cd /usr/share/ocsinventory-reports/ocsreports/crontab && php cron_all_software.php
      ocsinventory-job:
        type: cronjob
        cronjob:
          schedule: "0 0 * * *"
          concurrencyPolicy: "Replace"
          backoffLimit: 0
          failedJobsHistory: 1
          successfulJobsHistory: 0
        pod:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
        containers:
          app:
            image:
              repository: ghcr.io/sstr-dev/kubectl
              tag: 1.33.3@sha256-4ab498f9ad398c572e15ccf479276e0067fcd90832a2dffb77cd634aa29cd0f0
            command:
              - /bin/sh
              - -c
              - |
                POD=$(kubectl get pod -l app.kubernetes.io/name=ocsinventory -o jsonpath="{.items[0].metadata.name}")
                kubectl exec -n default $POD -c app -- \
                  sh -c 'cd /usr/share/ocsinventory-reports/ocsreports/crontab && php cron_all_software.php'
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 80

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_MAIN_DOMAIN_NAME}"
        parentRefs:
          - name: main
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    configMaps:
      config:
        enabled: true
        data:
          ocsinventory.ini: |
            upload_max_filesize = 200M
            post_max_size = 201M
            max_execution_time = -1
            max_input_time = -1
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: *app
        advancedMounts:
          ocsinventory:
            app:
              - subPath: "perlcomdata"
                path: "/etc/ocsinventory-server"
              - subPath: "ocsreportsdata"
                path: "/usr/share/ocsinventory-reports/ocsreports/extensions"
              - subPath: "varlibdata"
                path: "/var/lib/ocsinventory-reports"
              - subPath: "httpdconfdata"
                path: "/etc/apache2/conf-available"
              - subPath: "profilesconfdata"
                path: "/usr/share/ocsinventory-reports/ocsreports/config/profiles"
      config:
        type: configMap
        name: *app
        advancedMounts:
          ocsinventory:
            ocsinventory.ini:
              - path: /etc/php/8.1/apache2/conf.d/ocsinventory.ini
                readOnly: true
    rbac:
      roles:
        ocsinventory-job:
          type: ClusterRole
          rules:
          - apiGroups: [""]
            resources: ["pods", "pods/exec"]
            verbs: ["get", "list", "create", "delete"]

      bindings:
        ocsinventory-job:
          type: ClusterRoleBinding
          roleRef:
            identifier: ocsinventory-job
          subjects:
            - identifier: ocsinventory-job
