---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  labels:
    app.kubernetes.io/name: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-custom-templates
  labels:
    app.kubernetes.io/name: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-standard

