---
#- search:
#    provider: custom
#    url: https://kagi.com/search?q=
#    focus: false
#    target: _blank
#    suggestionUrl: https://kagi.com/api/autosuggest?q=
#    showSearchSuggestions: true
#- resources:
#    backend: kubernetes
#    cpu: true
#    expanded: true
#    memory: true
- search:
    provider: [duckduckgo, google]
    focus: false
    target: _blank
- greeting:
    text_size: xl
    text: "Howdy Hey!"
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: main
    nodes:
      show: false
      cpu: true
      memory: true
      showLabel: true
- openmeteo:
    label: Home
    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
    timezone: ${CLUSTER_TIMEZONE}
    units: metric
    cache: 5
- datetime:
    text_size: l
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23
