---
# yaml-language-server: $schema=https://schemas.sstr.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/base/dev/forgejo
  dependsOn:
    - name: volsync
      namespace: storage
  postBuild:
    substitute:
      APP: *app
      CLUSTER: ${CLUSTER}
      VOLSYNC_CAPACITY: 16Gi
      LB_SERVICE_IP: 10.0.60.59
      LB_SERVICE_SEGMENT: servers
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: ns-dev-secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://schemas.sstr.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-runner
spec:
  interval: 15m
  path: ./kubernetes/apps/base/dev/forgejo-runner
  postBuild:
    substitute:
      APP: *app
      CLUSTER: ${CLUSTER}
  dependsOn:
    - name: forgejo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false

