# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: &namespace self-hosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/self-hosted/paperless
  postBuild:
    substitute:
      APP: *app
      DMS_DATA_PATH: /opt/homelab/dms
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: tika
      namespace: *namespace
    - name: gotenberg
      namespace: *namespace
    - name: postgres-cluster
      namespace: database
    - name: external-secrets
      namespace: security
    - name: dragonfly-cluster
      namespace: database
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
