---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app actions-runner-home-ops
  namespace: &namespace actions-runner-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  retryInterval: 2m
  path: ./kubernetes/apps/base/actions-runner-system/actions-runner-controller/runners/home-ops-runner
  prune: true
  dependsOn:
    - name: actions-runner-controller-runners-base
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      CLUSTER: casa
      VOL_STORAGECLASS: local-hostpath
      VOL_CAPACITY: 1Gi
  targetNamespace: *namespace
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: &homerunner home-ops-runner
      namespace: *namespace
    - apiVersion: &apiVersion actions.github.com/v1alpha1
      kind: &kind AutoscalingRunnerSet
      namespace: *namespace
      name: *homerunner
  healthCheckExprs:
    - apiVersion: *apiVersion
      kind: *kind
      failed: status.currentRunners == 0 && status.pendingEphemeralRunners == 0 && status.runningEphemeralRunners == 0
      current: status.currentRunners > 0

#---
## yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &app actions-runner-controller-runners
#spec:
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *app
#  interval: 1h
#  path: ./kubernetes/apps/base/actions-runner-system/actions-runner-controller/runners
#  postBuild:
#    substitute:
#      CLUSTER: utility
#  prune: true
#  retryInterval: 2m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  targetNamespace: actions-runner-system
#  timeout: 5m
#  wait: false
#  patches:
#  - patch: |-
#      apiVersion: helm.toolkit.fluxcd.io/v2
#      kind: HelmRelease
#      metadata:
#        name: home-ops-runner-utility
#      spec:
#        values:
#          template:
#            spec:
#              securityContext:
#                fsGroup: 123
#    target:
#      kind: HelmRelease
