---
apiVersion: v1
kind: ConfigMap
metadata:
  name: downloads-gateway
  labels:
    app.kubernetes.io/instance: downloads-gateway
    app.kubernetes.io/name: downloads-gateway
data:
  nat.conf: |
    # Placeholder
  nat6.conf: |
    # Placeholder
  settings.sh: |
    #!/bin/sh
    DNS_LOCAL_CIDRS="local cluster.local ${DOMAIN} ${SECRET_MAIN_DOMAIN_NAME}"
    IPV4_ENABLED="true"
    IPV6_ENABLED="false"
    NOT_ROUTED_TO_GATEWAY_CIDRS="${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR}"
    VPN_BLOCK_OTHER_TRAFFIC="false"
    VPN_INTERFACE="wg0"
    VPN_LOCAL_CIDRS="${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR} ${LOCAL_CIDR_1}"
    VPN_TRAFFIC_PORT="51820"
    VXLAN_GATEWAY_FIRST_DYNAMIC_IP="20"
    VXLAN_ID="44"
    VXLAN_IP_NETWORK="172.16.1"
    VXLAN_PORT="4789"



