apiVersion: v1
kind: Secret
metadata:
    name: ns-network-secret
stringData:
    K8SGTWDOMAINS: ENC[AES256_GCM,data:2mHgwbYChe4r6rlcR+FXnp7GruulPS7BaNvzWQuQ/Tpf38qV3CGLf089tjXv/iBlJE06rVu5,iv:WhN8CkaAj8ffH8FELhuDgMlrL/NqwqDazmtYZ1xXHvI=,tag:FVmPiyo9R92O1ltZTGxpwQ==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T21:26:02Z"
    mac: ENC[AES256_GCM,data:rQBcW43ja0n28Pb2xl5m5itCGfsmYq/OqdQ/n6EQrX5zLaYBCZgn4QfzISfwKl0ShbmwKGQc0+4Q/8jiGr4w26OGbV7YVsczcR1j3LHEWdGkxmP/tjKpNsZwcpWUQktl8Xi6v++JODdgPUAscb0aIAIQD+PYiHCsNQ+wijgOw1w=,iv:7FSRqkRIo6SeNoy6MOvVi5seMtm9bepOycl6THo+KhM=,tag:1EI8nv4I4TNnO1hz376n4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
