apiVersion: v1
kind: Secret
metadata:
    name: ns-security-secret
stringData:
    VAULT_SERVER: ENC[AES256_GCM,data:MleuZPPiC/1f2bTlP02Sc5Tt2hRSrTVHwINnZ5ysZjyv5eb2qOAFrUqI+XtC3B9ifz8=,iv:YCeIDk+3mkYaaHmtD3VYw79NAkq7SJghwKGHKKB41Dk=,tag:fTMwG6PvHU0FXOJCEWUjqg==,type:str]
    VAULT_USER: ENC[AES256_GCM,data:Y55C8e/vFY7M/tKI,iv:Jx77iZEutc9KsBldRxvKBwxFu0xkVX1rnXM1bDzXznE=,tag:x+6y6Ay8x4yjwQ0WeKAo0w==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T21:25:44Z"
    mac: ENC[AES256_GCM,data:PLOj0Z9WQHCKF8BnJLWKNj0utMGMrHDrfUc2J5YywWpCtvgGvVYjh/hdKxb53gnswlK+7Ou6BjXUQD4B9FliRRJQnOk+3TlqnRw/GvQb4t4u8k5oUcJ5wrU6U9geJ7Z5B9k1h56HVprihvJylyaGkrPuReB8a4ugbDW8JR0+uu0=,iv:qxboJm0YhIzWl/n5VVgEl2UISFuO7hmW3QcQFdg34BU=,tag:V7eg7luJHNNienQrLaVQ7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
