---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-selfsigned-issuer
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name cluster-signed-issuer
spec:
  isCA: true
  commonName: *name
  subject:
    organizations:
      - '${SECRET_PRIVATE_DOMAIN}'
  secretName: cluster-signed-issuer-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-signed-issuer
spec:
  ca:
    secretName: cluster-signed-issuer-secret
