---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-basic-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${SECRET_STORE:-vault-backend}
  target:
    name: ${APP}-basic-auth-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        .htpasswd: "{{ .${BASIC_AUTH_SECRET_KEY:-htpasswd} }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/${APP}
