#---
## yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &app downloads-gateway
#spec:
#  targetNamespace: &namespace vpn-gateway
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *app
#  interval: 1h
#  path: ./kubernetes/apps/base/vpn-gateway/downloads-gateway/app
#  healthChecks:
#    - apiVersion: helm.toolkit.fluxcd.io/v2
#      kind: HelmRelease
#      name: *app
#      namespace: *namespace
#  postBuild:
#    substitute:
#      APP: *app
#    substituteFrom:
#      - kind: ConfigMap
#        name: cluster-settings
#      - kind: Secret
#        name: cluster-secrets
#  prune: true
#  retryInterval: 2m
#  dependsOn:
#    - name: downloads-gateway-config
#    - name: external-secrets
#      namespace: security
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  timeout: 5m
#  #wait: false
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &app downloads-gateway-webhook
#spec:
#  targetNamespace: &namespace vpn-gateway
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *app
#  dependsOn:
#    - name: cert-manager
#      namespace: cert-manager
#    - name: downloads-gateway
#  healthChecks:
#    - apiVersion: helm.toolkit.fluxcd.io/v2
#      kind: HelmRelease
#      name: *app
#      namespace: *namespace
#  postBuild:
#    substitute:
#      APP: *app
#    substituteFrom:
#      - kind: ConfigMap
#        name: cluster-settings
#      - kind: Secret
#        name: cluster-secrets
#  path: ./kubernetes/apps/base/vpn-gateway/downloads-gateway/webhook
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  interval: 1h
#  retryInterval: 2m
#  timeout: 5m
#
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app downloads-gateway
spec:
  targetNamespace: &namespace vpn-gateway
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  path: ./kubernetes/apps/base/vpn-gateway/downloads-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
