---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gatus-secret
    template:
      data:
        PUSHOVER_TOKEN: "{{ .GATUS_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .GATUS_PUSHOVER_USER_KEY }}"
        OIDC_ISSUER: "{{ .GATUS_OIDC_ISSUER }}"
        OIDC_CLIENT_ID: "{{ .GATUS_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .GATUS_OIDC_CLIENT_SECRET }}"
        # Database
        POSTGRES_URI: |-
          postgres://{{ .GATUS_POSTGRES_USER }}:{{ .GATUS_POSTGRES_PASSWORD }}@{{ .GATUS_POSTGRES_HOST }}/{{ .GATUS_POSTGRES_DB }}

  dataFrom:
    - extract:
        key: ${CLUSTER}/gatus
