---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mariadb-secret
    template:
      data:
        MYSQL_ROOT_PASSWORD: "{{ .MYSQL_ROOT_PASSWORD }}"
        MYSQL_USER: "{{ .MYSQL_APP_USER }}"
        MYSQL_DATABASE: "{{ .MYSQL_APP_DATABASE }}"
        MYSQL_PASSWORD: "{{ .MYSQL_APP_PASSWORD }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/mariadb

