---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pgadmin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        PGADMIN_DEFAULT_EMAIL: '{{ .PGADMIN_DEFAULT_EMAIL }}'
        PGADMIN_DEFAULT_PASSWORD: '{{ .PGADMIN_DEFAULT_PASSWORD }}'
        config_local.py: |
          AUTHENTICATION_SOURCES = ['oauth2'] #, 'internal']
          OAUTH2_AUTO_CREATE_USER = True
          MASTER_PASSWORD_REQUIRED = False
          OAUTH2_CONFIG = [{
              'OAUTH2_NAME' : 'authentik',
              'OAUTH2_DISPLAY_NAME' : 'CasaID',
              'OAUTH2_CLIENT_ID' : '{{ .client_id }}',
              'OAUTH2_CLIENT_SECRET' : '{{ .client_secret }}',
              'OAUTH2_TOKEN_URL' : 'https://${SECRET_SSO_DOMAIN}/application/o/token/',
              'OAUTH2_AUTHORIZATION_URL' : 'https://${SECRET_SSO_DOMAIN}/application/o/authorize/',
              'OAUTH2_API_BASE_URL' : 'https://${SECRET_SSO_DOMAIN}/',
              'OAUTH2_USERINFO_ENDPOINT' : 'https://${SECRET_SSO_DOMAIN}/application/o/userinfo/',
              'OAUTH2_SERVER_METADATA_URL' : '{{ .openid_config }}',
              'OAUTH2_SCOPE' : 'openid email profile',
              'OAUTH2_ICON' : 'fa-openid',
              'OAUTH2_BUTTON_COLOR' : '#2db1fd'
          }]
        pgpass: |
          *:*:*:{{ .POSTGRES_SUPER_USER }}:{{ .POSTGRES_SUPER_PASS }}
        servers.json: |
          {
            "Servers": {
              "1": {
                "Name": "postgres-cluster",
                "Group": "Servers",
                "Host": "postgres-cluster-rw.database.svc.cluster.local",
                "Port": 5432,
                "Shared": true,
                "MaintenanceDB": "postgres",
                "Username": "{{ .POSTGRES_SUPER_USER }}",
                "SharedUsername": "{{ .POSTGRES_SUPER_USER }}",
                "ConnectionParameters": {
                  "passfile": ".pgpass",
                  "sslmode": "prefer"
                },
                "SSLCompression": 0,
                "Timeout": 10,
                "UseSSHTunnel": 0,
                "TunnelPort": "22",
                "TunnelAuthentication": 0
              }
            }
          }

  dataFrom:
    - extract:
        key: ${CLUSTER}/pgadmin
    - extract:
        key: ${CLUSTER}/cloudnative-pg
    - extract:
        key: ${CLUSTER}/openid/pgadmin
