# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app lldap
spec:
  interval: 1h
  path: ./kubernetes/apps/base/security/lldap
  postBuild:
    substitute:
      APP: *app
      REPLICAS: "2"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: external-secrets
      namespace: external-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
