apiVersion: v1
kind: Secret
metadata:
    name: ns-network-secret
stringData:
    K8SGTWDOMAINS: ENC[AES256_GCM,data:qO3ruzf8sw+G5sa4lzah0hbtfLvwh9PKpsF79keWc8jC8WZuWe6FWfzx242xc4SjjUifxSDk,iv:nNTrTl0iY67ed70DO9xqNp2P/rw80Lt0cY2I8hRA114=,tag:eItrWeyuwRA/nHppJkEduQ==,type:str]
sops:
    age:
        - recipient: age13x3gvqpe83vx0rcmcdcqnt202c4rsq3sax8s5q2p5t2lcjflpsvqgng8s3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU1BZnl6UlNZTDZ1WVBQ
            bjRJVlIxMGloeHdHeVZxaE5VckJnVno5TkZjClZLNWQ3bExId1dXcVhvNHpFaWhM
            Z2ZlMWh2Q0xScS9vTWlleklrMEJWMmsKLS0tIGtPREpnRHVuV3lMOTAyS1R1NEhv
            Vno5dDJPbVF3M1FYUVFXSGFwRUJmZlkKQLQaW2yB3o26/lfoFRw9QLj8/YauCZDh
            GzL3OsXvRHQ3REWUJHtWh1GZIcKnehG2NBxL2OnE/+oenD9oSkDbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T16:49:38Z"
    mac: ENC[AES256_GCM,data:DN6wH8Kd2+187VANvqlqYnFAwdoXcwJvTK0r9IcEh0Wh20viqaGe+EiJ+y8JZ2GuTZllLIJ8GQVdXs5NhVj8VSPejWr6gMcFl8G4M6yO/7rP82u3SahnmnvSOix1g+2PmogvER29Ii+nQYOq7EWh5JLFXRX55QS4RmFcdPPKf1U=,iv:e3CRfU3Buh9TCSYHZmNNgRIaGemZGWq5+Wbx/SRJ7WU=,tag:GUu2USz+lF36uowGi+kg9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
