apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &sname ${APP}-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *sname
    creationPolicy: Owner
  data: []
  dataFrom:
    - extract:
        key: ${CLUSTER}/${APP}

