---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filaman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: filaman-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # https://docu.filaman.app/

        #===SECURIRY CONFIGURATION===
        SECRET_KEY: "{{ .FILAMAN_SECRET_KEY }}"
        CSRF_SECRET_KEY: "{{ .FILAMAN_CSRF_SECRET_KEY }}"

        #===USER CONFIGURATION===

        # ===========================================
        # Administrator Account
        # ===========================================
        # These credentials are used to create the admin account on first start
        ADMIN_EMAIL: "{{ .FILAMAN_ADMIN_EMAIL }}"
        ADMIN_PASSWORD: "{{ .FILAMAN_ADMIN_PASSWORD }}"
        ADMIN_DISPLAY_NAME: "{{ .FILAMAN_ADMIN_DISPLAY_NAME }}"
        ADMIN_LANGUAGE: "{{ .FILAMAN_ADMIN_LANGUAGE }}"
        ADMIN_SUPERADMIN: "{{ .FILAMAN_ADMIN_SUPERADMIN }}"
        
        #===DATABASE CONFIGURATION===
        # postgresql+asyncpg://username:password@hostname:3306/database
        DATABASE_URL: "postgresql+asyncpg://{{ .FILAMAN_POSTGRES_USER }}:{{ .FILAMAN_POSTGRES_PASSWORD }}@{{ .FILAMAN_POSTGRES_HOST }}/{{ .FILAMAN_POSTGRES_DB }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/filaman

