---
# yaml-language-server: $schema=https://schemas.sstr.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ntfy-secret
    template:
      data:
        # postgres
        NTFY_DATABASE_URL: "postgres://{{ .NTFY_POSTGRES_USER }}:{{ .NTFY_POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/{{ .NTFY_POSTGRES_DB }}"
  dataFrom:
    - extract:
        key: ${CLUSTER}/ntfy
