---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
components:
  - ../../../components/common
  - ../../../vars/casa
resources:
  - ../../../vars/casa/ns/security-secrets.sops.yaml
  - ./it-tools.yaml
  #- ./openspeedtest/ks.yaml
  - ./cyberchef.yaml
  #- ./photon/ks.yaml
  - ./homepage.yaml
  - ./snipe-it.yaml
  - ./drawio.yaml
  #- ./part-db.yaml # mysql not work, remove it
  - ./paperless-gotenberg.yaml
  - ./paperless-tika.yaml
  - ./paperless.yaml
  #- ./tandoor.yaml
  - ./mealie.yaml
  - ./opencloud.yaml
  #- ./ocis.yaml
  #- ./convertx.yaml
  - ./change-detection.yaml
  - ./privatebin.yaml
  - ./ocsinventory.yaml
