---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app snipe-it
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/self-hosted/snipe-it
  components:
    - ../../../../components/vol
    - ../../../../components/mariadb/database
  postBuild:
    substitute:
      APP: *app
      REPLICAS: "1"
      INGRESSCLASS: internal-nginx
      IOTINGRESS: "true"
      DEFAULTINGRESSEN: "false"
      DATABASE: snipeit
      MAX_CON: "25"
      VOL_CAPACITY: 5Gi
      VOL_STORAGECLASS: sc-standard
      VOL_ACCESSMODES: ReadWriteMany
      VOL_RESOURCEPOLICY: keep

    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: mariadb-cluster
      namespace: database
    - name: external-secrets
      namespace: security
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  timeout: 5m
  wait: false
