kind: ConfigMap
apiVersion: v1
metadata:
  name: sc-fast-local-path-config
  namespace: storage-system
data:
  config.json: |-
    {
      "sharedFileSystemPath": "${SCFASTPATH}"
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
    chmod 700 "$VOL_DIR/.."
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
      namespace: storage-system
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
                - key: homelab.k8s.io/type
                  operator: In
                  values:
                    - ct
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
