---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    defaultVolumeType: "hostPath"
provisioner: cluster.local/sc-fast-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  pathPattern: '{{ .PVC.Namespace }}-{{ .PVC.Name }}'

