---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: lldap
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_USER_DN: "{{ .LLDAP_USER_DN }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        LLDAP_DATABASE_URL: "postgres://lldap:{{ .sql_lldap }}@postgres-cluster-rw.database.svc.cluster.local/lldap"
  dataFrom:
    - extract:
        key: ${CLUSTER}/lldap
    - extract:
        key: ${CLUSTER}/pg-users
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sql_$1"
