# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app influx
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/base/database/influx
  components:
    - ../../../../components/vol
  postBuild:
    substitute:
      APP: *app
      VOL_CAPACITY: 1Gi
      VOL_STORAGECLASS: sc-standard
      VOL_ACCESSMODES: ReadWriteMany
      VOL_RESOURCEPOLICY: keep
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  timeout: 5m
  wait: true
