---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
components:
  - ../../../components/common
  - ../../../vars/casa
resources:
  - ./cnpg.yaml
  #- ./crunchy-postgres.yaml
  - ./dragonfly/ks.yaml
  - ./dragonfly/cluster/ks.yaml
  - ./mongodb/ks.yaml
  - ./mariadb.yaml
  #- ./mongodb/cluster/ks.yaml
  #- ./kubeblocks/ks.yaml
  #- ./kubeblocks/addons/ks.yaml
  #- ./kubeblocks/backups/ks.yaml
  #- ./kubeblocks/clusters/ks.yaml
  #- ./kubeblocks/ingress/ks.yaml
  - ./dbgate.yaml
  - ./influx.yaml
